<%@ Page Language="c#" MasterPageFile="~/nsurveyadmin/MsterPageTabs.master" AutoEventWireup="false" Inherits="Votations.NSurvey.WebAdmin.HelpFiles" Codebehind="default.aspx.cs" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server"><div id="helpPanel"><div>
                <asp:ImageButton ID="btnBack" ImageUrl="~/Images/index-icon.png" runat="server" CssClass="buttonIndex"
                    PostBackUrl="~/NSurveyAdmin/Help/default.aspx#SurveyManagement" Visible="True" ToolTip="Back to Helpfiles Index" />
            </div><div>
            <h2 style="color:#5720C6;">Error Logging</h2><hr style="color:#e2e2e2;" />

            As part of the error handling features of SP&trade; (certain) system errors are written and saved (logged)
                to an error logfile.
                <br /><br />
                The logfile which is a basic textfile (.txt) can be found in the <code>App_Data</code> directory of the webapplication. 
                It can be opened, read and edited with any texteditor (e.g. notepad) if necessary.
                <br /> <br />
                To make is easier to monitor and read any system error messages the file can be accessed by administrators
                through the webapplication itself instead of having to access it on the webserver through FTP.
                                 <br /> <br />
                To edit or clear (CTRL+A to select all, next Delete) the logfile there is the option to <code>Save Changes</code> by clicking 
                the button.

                 <br /> <br />
                To read and edit the content of the file go to<br /><br />
                <pre>Menu: Surveys/ System Settings/ Errorlog</pre>
              <br />
                <i>Error Log Messages Content</i><br /> <br />
                The following entries (per error) are registered in the errorlog:<br />
                <br />Date and time

                <br />Exception Type
                <br />Exception Message
                <br />Source
                <br />Stack Trace
                               
                <br />
                <br />
                Inner Exception Type
                <br />Inner Exception
                <br />Inner Source
                <br />Inner Stack Trace
                    <br />
                <br />
                Note: not all entries may be shown or contain information depending on the type of error generated by the system or 
                the code.

                <hr style="color:#e2e2e2;" />
                <h3>More Information</h3><br />
                <a href="InstallationSettings.aspx">System settings</a><br />

                    </div>
<div id="fillerDiv" class="fillerDiv">&nbsp;</div></div></asp:Content>
