use [YourDBName]

-- delete old data
-- Truncate does not work because of ForeignKey
-- warning: also removes vts_tbsurveylanguage entries
GO
delete from vts_tbmultilanguage
GO
--- new languagecodes 2017 - sp25

INSERT [dbo].[vts_tbMultiLanguage] ([LanguageCode], [LanguageDescription]) VALUES
('aa', 'Afar_aa'),
('aa-DJ', 'Afar_Djibouti_aa-DJ'),
('aa-ER', 'Afar_Eritrea_aa-ER'),
('aa-ET', 'Afar_Ethiopia_aa-ET'),
('af', 'Afrikaans_af'),
('af-NA', 'Afrikaans_Namibia_af-NA'),
('af-ZA', 'Afrikaans_South Africa_af-ZA'),
('agq', 'Aghem_agq'),
('agq-CM', 'Aghem_Cameroon_agq-CM'),
('ak', 'Akan_ak'),
('ak-GH', 'Akan_Ghana_ak-GH'),
('sq', 'Albanian_sq'),
('sq-AL', 'Albanian_Albania_sq-AL'),
('sq-MK', 'Albanian_Macedonia, FYRO_sq-MK'),
('gsw', 'Alsatian_gsw'),
('gsw-FR', 'Alsatian_France_gsw-FR'),
('gsw-LI', 'Alsatian_Liechtenstein_gsw-LI'),
('gsw-CH', 'Alsatian_Switzerland_gsw-CH'),
('am', 'Amharic_am'),
('am-ET', 'Amharic_Ethiopia_am-ET'),
('ar', 'Arabic_ar'),
('ar-DZ', 'Arabic_Algeria_ar-DZ'),
('ar-BH', 'Arabic_Bahrain_ar-BH'),
('ar-TD', 'Arabic_Chad_ar-TD'),
('ar-KM', 'Arabic_Comoros_ar-KM'),
('ar-DJ', 'Arabic_Djibouti_ar-DJ'),
('ar-EG', 'Arabic_Egypt_ar-EG'),
('ar-ER', 'Arabic_Eritrea_ar-ER'),
('ar-IQ', 'Arabic_Iraq_ar-IQ'),
('ar-IL', 'Arabic_Israel_ar-IL'),
('ar-JO', 'Arabic_Jordan_ar-JO'),
('ar-KW', 'Arabic_Kuwait_ar-KW'),
('ar-LB', 'Arabic_Lebanon_ar-LB'),
('ar-LY', 'Arabic_Libya_ar-LY'),
('ar-MR', 'Arabic_Mauritania_ar-MR'),
('ar-MA', 'Arabic_Morocco_ar-MA'),
('ar-OM', 'Arabic_Oman_ar-OM'),
('ar-PS', 'Arabic_Palestinian Authority_ar-PS'),
('ar-QA', 'Arabic_Qatar_ar-QA'),
('ar-SA', 'Arabic_Saudi Arabia_ar-SA'),
('ar-SO', 'Arabic_Somalia_ar-SO'),
('ar-SS', 'Arabic_South Sudan_ar-SS'),
('ar-SD', 'Arabic_Sudan_ar-SD'),
('ar-SY', 'Arabic_Syria_ar-SY'),
('ar-TN', 'Arabic_Tunisia_ar-TN'),
('ar-AE', 'Arabic_U.A.E._ar-AE'),
('ar-001', 'Arabic_World_ar-001'),
('ar-YE', 'Arabic_Yemen_ar-YE'),
('hy', 'Armenian_hy'),
('hy-AM', 'Armenian_Armenia_hy-AM'),
('as', 'Assamese_as'),
('as-IN', 'Assamese_India_as-IN'),
('ast', 'Asturian_ast'),
('ast-ES', 'Asturian_Spain_ast-ES'),
('asa', 'Asu_asa'),
('asa-TZ', 'Asu_Tanzania_asa-TZ'),
('az-Cyrl', 'Azerbaijani (Cyrillic)_az-Cyrl'),
('az-Cyrl-AZ', 'Azerbaijani (Cyrillic)_Azerbaijan_az-Cyrl-AZ'),
('az', 'Azerbaijani (Latin)_az'),
('az-Latn', 'Azerbaijani (Latin)_az-Latn'),
('az-Latn-AZ', 'Azerbaijani (Latin)_Azerbaijan_az-Latn-AZ'),
('ksf', 'Bafia_ksf'),
('ksf-CM', 'Bafia_Cameroon_ksf-CM'),
('bm', 'Bamanankan_bm'),
('bm-Latn-ML', 'Bamanankan (Latin)_Mali_bm-Latn-ML'),
('bn', 'Bangla_bn'),
('bn-BD', 'Bangla_Bangladesh_bn-BD'),
('bn-IN', 'Bangla_India_bn-IN'),
('bas', 'Basaa_bas'),
('bas-CM', 'Basaa_Cameroon_bas-CM'),
('ba', 'Bashkir_ba'),
('ba-RU', 'Bashkir_Russia_ba-RU'),
('eu', 'Basque_eu'),
('eu-ES', 'Basque_Spain_eu-ES'),
('be', 'Belarusian_be'),
('be-BY', 'Belarusian_Belarus_be-BY'),
('bem', 'Bemba_bem'),
('bem-ZM', 'Bemba_Zambia_bem-ZM'),
('bez', 'Bena_bez'),
('bez-TZ', 'Bena_Tanzania_bez-TZ'),
('byn', 'Blin_byn'),
('byn-ER', 'Blin_Eritrea_byn-ER'),
('brx', 'Bodo_brx'),
('brx-IN', 'Bodo_India_brx-IN'),
('bs-Cyrl', 'Bosnian (Cyrillic)_bs-Cyrl'),
('bs-Cyrl-BA', 'Bosnian (Cyrillic)_Bosnia and Herzegovina_bs-Cyrl-BA'),
('bs-Latn', 'Bosnian (Latin)_bs-Latn'),
('bs', 'Bosnian (Latin)_bs'),
('bs-Latn-BA', 'Bosnian (Latin)_Bosnia and Herzegovina_bs-Latn-BA'),
('br', 'Breton_br'),
('br-FR', 'Breton_France_br-FR'),
('bg', 'Bulgarian_bg'),
('bg-BG', 'Bulgarian_Bulgaria_bg-BG'),
('my', 'Burmese_my'),
('my-MM', 'Burmese_Myanmar_my-MM'),
('ca', 'Catalan_ca'),
('ca-AD', 'Catalan_Andorra_ca-AD'),
('ca-FR', 'Catalan_France_ca-FR'),
('ca-IT', 'Catalan_Italy_ca-IT'),
('ca-ES', 'Catalan_Spain_ca-ES'),
('tzm-Latn-MA', 'Central Atlas Tamazight (Latin)_Morocco_tzm-Latn-MA'),
('ku', 'Central Kurdish_ku'),
('ku-Arab', 'Central Kurdish_ku-Arab'),
('ku-Arab-IQ', 'Central Kurdish_Iraq_ku-Arab-IQ'),
('cd-RU', 'Chechen_Russia_cd-RU'),
('chr', 'Cherokee_chr'),
('chr-Cher', 'Cherokee_chr-Cher'),
('chr-Cher-US', 'Cherokee_United States_chr-Cher-US'),
('cgg', 'Chiga_cgg'),
('cgg-UG', 'Chiga_Uganda_cgg-UG'),
('zh-Hans', 'Chinese (Simplified)_zh-Hans'),
('zh', 'Chinese (Simplified)_zh'),
('zh-CN', 'Chinese (Simplified)_People''s Republic of China_zh-CN'),
('zh-SG', 'Chinese (Simplified)_Singapore_zh-SG'),
('zh-Hant', 'Chinese (Traditional)_zh-Hant'),
('zh-HK', 'Chinese (Traditional)_Hong Kong S.A.R._zh-HK'),
('zh-MO', 'Chinese (Traditional)_Macao S.A.R._zh-MO'),
('zh-TW', 'Chinese (Traditional)_Taiwan_zh-TW'),
('cu-RU', 'Church Slavic_Russia_cu-RU'),
('swc', 'Congo Swahili_swc'),
('swc-CD', 'Congo Swahili_Congo DRC_swc-CD'),
('kw', 'Cornish_kw'),
('kw-GB', 'Cornish_United Kingdom_kw-GB'),
('co', 'Corsican_co'),
('co-FR', 'Corsican_France_co-FR'),
('bs, hr, or sr', 'Croatian_bs, hr, or sr'),
('hr-HR', 'Croatian_Croatia_hr-HR'),
('hr-BA', 'Croatian (Latin)_Bosnia and Herzegovina_hr-BA'),
('cs', 'Czech_cs'),
('cs-CZ', 'Czech_Czech Republic_cs-CZ'),
('da', 'Danish_da'),
('da-DK', 'Danish_Denmark_da-DK'),
('da-GL', 'Danish_Greenland_da-GL'),
('prs', 'Dari_prs'),
('prs-AF', 'Dari_Afghanistan_prs-AF'),
('dv', 'Divehi_dv'),
('dv-MV', 'Divehi_Maldives_dv-MV'),
('dua', 'Duala_dua'),
('dua-CM', 'Duala_Cameroon_dua-CM'),
('nl', 'Dutch_nl'),
('nl-AW', 'Dutch_Aruba_nl-AW'),
('nl-BE', 'Dutch_Belgium_nl-BE'),
('nl-BQ', 'Dutch_Bonaire, Sint Eustatius and Saba_nl-BQ'),
('nl-CW', 'Dutch_Curaçao_nl-CW'),
('nl-NL', 'Dutch_Netherlands_nl-NL'),
('nl-SX', 'Dutch_Sint Maarten_nl-SX'),
('nl-SR', 'Dutch_Suriname_nl-SR'),
('dz', 'Dzongkha_dz'),
('dz-BT', 'Dzongkha_Bhutan_dz-BT'),
('ebu', 'Embu_ebu'),
('ebu-KE', 'Embu_Kenya_ebu-KE'),
('en', 'English_en'),
('en-AS', 'English_American Samoa_en-AS'),
('en-AI', 'English_Anguilla_en-AI'),
('en-AG', 'English_Antigua and Barbuda_en-AG'),
('en-AU', 'English_Australia_en-AU'),
('en-AT', 'English_Austria_en-AT'),
('en-BS', 'English_Bahamas_en-BS'),
('en-BB', 'English_Barbados_en-BB'),
('en-BE', 'English_Belgium_en-BE'),
('en-BZ', 'English_Belize_en-BZ'),
('en-BM', 'English_Bermuda_en-BM'),
('en-BW', 'English_Botswana_en-BW'),
('en-IO', 'English_British Indian Ocean Territory_en-IO'),
('en-VG', 'English_British Virgin Islands_en-VG'),
('en-BI', 'English_Burundi_en-BI'),
('en-CM', 'English_Cameroon_en-CM'),
('en-CA', 'English_Canada_en-CA'),
('en-029', 'English_Caribbean_en-029'),
('en-KY', 'English_Cayman Islands_en-KY'),
('en-CX', 'English_Christmas Island_en-CX'),
('en-CC', 'English_Cocos [Keeling] Islands_en-CC'),
('en-CK', 'English_Cook Islands_en-CK'),
('en-CY', 'English_Cyprus_en-CY'),
('en-DK', 'English_Denmark_en-DK'),
('en-DM', 'English_Dominica_en-DM'),
('en-ER', 'English_Eritrea_en-ER'),
('en-150', 'English_Europe_en-150'),
('en-FK', 'English_Falkland Islands_en-FK'),
('en-FI', 'English_Finland_en-FI'),
('en-FJ', 'English_Fiji_en-FJ'),
('en-GM', 'English_Gambia_en-GM'),
('en-DE', 'English_Germany_en-DE'),
('en-GH', 'English_Ghana_en-GH'),
('en-GI', 'English_Gibraltar_en-GI'),
('en-GD', 'English_Grenada_en-GD'),
('en-GU', 'English_Guam_en-GU'),
('en-GG', 'English_Guernsey_en-GG'),
('en-GY', 'English_Guyana_en-GY'),
('en-HK', 'English_Hong Kong_en-HK'),
('en-IN', 'English_India_en-IN'),
('en-IE', 'English_Ireland_en-IE'),
('en-IM', 'English_Isle of Man_en-IM'),
('en-IL', 'English_Israel_en-IL'),
('en-JM', 'English_Jamaica_en-JM'),
('en-JE', 'English_Jersey_en-JE'),
('en-KE', 'English_Kenya_en-KE'),
('en-KI', 'English_Kiribati_en-KI'),
('en-LS', 'English_Lesotho_en-LS'),
('en-LR', 'English_Liberia_en-LR'),
('en-MO', 'English_Macao SAR_en-MO'),
('en-MG', 'English_Madagascar_en-MG'),
('en-MW', 'English_Malawi_en-MW'),
('en-MY', 'English_Malaysia_en-MY'),
('en-MT', 'English_Malta_en-MT'),
('en-MH', 'English_Marshall Islands_en-MH'),
('en-MU', 'English_Mauritius_en-MU'),
('en-FM', 'English_Micronesia_en-FM'),
('en-MS', 'English_Montserrat_en-MS'),
('en-NA', 'English_Namibia_en-NA'),
('en-NR', 'English_Nauru_en-NR'),
('en-NL', 'English_Netherlands_en-NL'),
('en-NZ', 'English_New Zealand_en-NZ'),
('en-NG', 'English_Nigeria_en-NG'),
('en-NU', 'English_Niue_en-NU'),
('en-NF', 'English_Norfolk Island_en-NF'),
('en-MP', 'English_Northern Mariana Islands_en-MP'),
('en-PK', 'English_Pakistan_en-PK'),
('en-PW', 'English_Palau_en-PW'),
('en-PG', 'English_Papua New Guinea_en-PG'),
('en-PN', 'English_Pitcairn Islands_en-PN'),
('en-PR', 'English_Puerto Rico_en-PR'),
('en-PH', 'English_Republic of the Philippines_en-PH'),
('en-RW', 'English_Rwanda_en-RW'),
('en-KN', 'English_Saint Kitts and Nevis_en-KN'),
('en-LC', 'English_Saint Lucia_en-LC'),
('en-VC', 'English_Saint Vincent and the Grenadines_en-VC'),
('en-WS', 'English_Samoa_en-WS'),
('en-SC', 'English_Seychelles_en-SC'),
('en-SL', 'English_Sierra Leone_en-SL'),
('en-SG', 'English_Singapore_en-SG'),
('en-SX', 'English_Sint Maarten_en-SX'),
('en-SI', 'English_Slovenia_en-SI'),
('en-SB', 'English_Solomon Islands_en-SB'),
('en-ZA', 'English_South Africa_en-ZA'),
('en-SS', 'English_South Sudan_en-SS'),
('en-SH', 'English_St Helena, Ascension, Tristan da Cunha_en-SH'),
('en-SD', 'English_Sudan_en-SD'),
('en-SZ', 'English_Swaziland_en-SZ'),
('en-SE', 'English_Sweden_en-SE'),
('en-CH', 'English_Switzerland_en-CH'),
('en-TZ', 'English_Tanzania_en-TZ'),
('en-TK', 'English_Tokelau_en-TK'),
('en-TO', 'English_Tonga_en-TO'),
('en-TT', 'English_Trinidad and Tobago_en-TT'),
('en-TC', 'English_Turks and Caicos Islands_en-TC'),
('en-TV', 'English_Tuvalu_en-TV'),
('en-UG', 'English_Uganda_en-UG'),
('en-GB', 'English_United Kingdom_en-GB'),
('en-US', 'English_United States_en-US'),
('en-UM', 'English_US Minor Outlying Islands_en-UM'),
('en-VI', 'English_US Virgin Islands_en-VI'),
('en-VU', 'English_Vanuatu_en-VU'),
('en-001', 'English_World_en-001'),
('en-ZM', 'English_Zambia_en-ZM'),
('en-ZW', 'English_Zimbabwe_en-ZW'),
('eo', 'Esperanto_eo'),
('eo-001', 'Esperanto_World_eo-001'),
('et', 'Estonian_et'),
('et-EE', 'Estonian_Estonia_et-EE'),
('ee', 'Ewe_ee'),
('ee-GH', 'Ewe_Ghana_ee-GH'),
('ee-TG', 'Ewe_Togo_ee-TG'),
('ewo', 'Ewondo_ewo'),
('ewo-CM', 'Ewondo_Cameroon_ewo-CM'),
('fo', 'Faroese_fo'),
('fo-DK', 'Faroese_Denmark_fo-DK'),
('fo-FO', 'Faroese_Faroe Islands_fo-FO'),
('fil', 'Filipino_fil'),
('fil-PH', 'Filipino_Philippines_fil-PH'),
('fi', 'Finnish_fi'),
('fi-FI', 'Finnish_Finland_fi-FI'),
('fr', 'French_fr'),
('fr-DZ', 'French_Algeria_fr-DZ'),
('fr-BE', 'French_Belgium_fr-BE'),
('fr-BJ', 'French_Benin_fr-BJ'),
('fr-BF', 'French_Burkina Faso_fr-BF'),
('fr-BI', 'French_Burundi_fr-BI'),
('fr-CM', 'French_Cameroon_fr-CM'),
('fr-CA', 'French_Canada_fr-CA'),
('fr-CF', 'French_Central African Republic_fr-CF'),
('fr-TD', 'French_Chad_fr-TD'),
('fr-KM', 'French_Comoros_fr-KM'),
('fr-CG', 'French_Congo_fr-CG'),
('fr-CD', 'French_Congo, DRC_fr-CD'),
('fr-CI', 'French_Côte d''Ivoire_fr-CI'),
('fr-DJ', 'French_Djibouti_fr-DJ'),
('fr-GQ', 'French_Equatorial Guinea_fr-GQ'),
('fr-FR', 'French_France_fr-FR'),
('fr-GF', 'French_French Guiana_fr-GF'),
('fr-PF', 'French_French Polynesia_fr-PF'),
('fr-GA', 'French_Gabon_fr-GA'),
('fr-GP', 'French_Guadeloupe_fr-GP'),
('fr-GN', 'French_Guinea_fr-GN'),
('fr-HT', 'French_Haiti_fr-HT'),
('fr-LU', 'French_Luxembourg_fr-LU'),
('fr-MG', 'French_Madagascar_fr-MG'),
('fr-ML', 'French_Mali_fr-ML'),
('fr-MQ', 'French_Martinique_fr-MQ'),
('fr-MR', 'French_Mauritania_fr-MR'),
('fr-MU', 'French_Mauritius_fr-MU'),
('fr-YT', 'French_Mayotte_fr-YT'),
('fr-MA', 'French_Morocco_fr-MA'),
('fr-NC', 'French_New Caledonia_fr-NC'),
('fr-NE', 'French_Niger_fr-NE'),
('fr-MC', 'French_Principality of Monaco_fr-MC'),
('fr-RE', 'French_Reunion_fr-RE'),
('fr-RW', 'French_Rwanda_fr-RW'),
('fr-BL', 'French_Saint Barthélemy_fr-BL'),
('fr-MF', 'French_Saint Martin_fr-MF'),
('fr-PM', 'French_Saint Pierre and Miquelon_fr-PM'),
('fr-SN', 'French_Senegal_fr-SN'),
('fr-SC', 'French_Seychelles_fr-SC'),
('fr-CH', 'French_Switzerland_fr-CH'),
('fr-SY', 'French_Syria_fr-SY'),
('fr-TG', 'French_Togo_fr-TG'),
('fr-TN', 'French_Tunisia_fr-TN'),
('fr-VU', 'French_Vanuatu_fr-VU'),
('fr-WF', 'French_Wallis and Futuna_fr-WF'),
('fy', 'Frisian_Frisland_fy'),
('fy-NL', 'Frisian_Netherlands_fy-NL'),
('fur', 'Friulian_fur'),
('fur-IT', 'Friulian_Italy_fur-IT'),
('ff', 'Fulah_ff'),
('ff-Latn', 'Fulah_ff-Latn'),
('ff-CM', 'Fulah_Cameroon_ff-CM'),
('ff-GN', 'Fulah_Guinea_ff-GN'),
('ff-MR', 'Fulah_Mauritania_ff-MR'),
('ff-Latn-SN', 'Fulah_Senegal_ff-Latn-SN'),
('gl', 'Galician_gl'),
('gl-ES', 'Galician_Spain_gl-ES'),
('lg', 'Ganda_lg'),
('lg-UG', 'Ganda_Uganda_lg-UG'),
('ka', 'Georgian_ka'),
('ka-GE', 'Georgian_Georgia_ka-GE'),
('de', 'German_de'),
('de-AT', 'German_Austria_de-AT'),
('de-BE', 'German_Belgium_de-BE'),
('de-DE', 'German_Germany_de-DE'),
('de-IT', 'German_Italy_de-IT'),
('de-LI', 'German_Liechtenstein_de-LI'),
('de-LU', 'German_Luxembourg_de-LU'),
('de-CH', 'German_Switzerland_de-CH'),
('el', 'Greek_el'),
('el-CY', 'Greek_Cyprus_el-CY'),
('el-GR', 'Greek_Greece_el-GR'),
('kl', 'Greenlandic_kl'),
('kl-GL', 'Greenlandic_Greenland_kl-GL'),
('gn', 'Guarani_gn'),
('gn-PY', 'Guarani_Paraguay_gn-PY'),
('gu', 'Gujarati_gu'),
('gu-IN', 'Gujarati_India_gu-IN'),
('guz', 'Gusii_guz'),
('guz-KE', 'Gusii_Kenya_guz-KE'),
('ha', 'Hausa (Latin)_ha'),
('ha-Latn', 'Hausa (Latin)_ha-Latn'),
('ha-Latn-GH', 'Hausa (Latin)_Ghana_ha-Latn-GH'),
('ha-Latn-NE', 'Hausa (Latin)_Niger_ha-Latn-NE'),
('ha-Latn-NG', 'Hausa (Latin)_Nigeria_ha-Latn-NG'),
('haw', 'Hawaiian_haw'),
('haw-US', 'Hawaiian_United States_haw-US'),
('he', 'Hebrew_he'),
('he-IL', 'Hebrew_Israel_he-IL'),
('hi', 'Hindi_hi'),
('hi-IN', 'Hindi_India_hi-IN'),
('hu', 'Hungarian_hu'),
('hu-HU', 'Hungarian_Hungary_hu-HU'),
('is', 'Icelandic_is'),
('is-IS', 'Icelandic_Iceland_is-IS'),
('ig', 'Igbo_ig'),
('ig-NG', 'Igbo_Nigeria_ig-NG'),
('id', 'Indonesian_id'),
('id-ID', 'Indonesian_Indonesia_id-ID'),
('ia', 'Interlingua_ia'),
('ia-FR', 'Interlingua_France_ia-FR'),
('ia-001', 'Interlingua_World_ia-001'),
('iu', 'Inuktitut (Latin)_iu'),
('iu-Latn', 'Inuktitut (Latin)_iu-Latn'),
('iu-Latn-CA', 'Inuktitut (Latin)_Canada_iu-Latn-CA'),
('iu-Cans', 'Inuktitut (Syllabics)_iu-Cans'),
('iu-Cans-CA', 'Inuktitut (Syllabics)_Canada_iu-Cans-CA'),
('ga', 'Irish_ga'),
('ga-IE', 'Irish_Ireland_ga-IE'),
('it', 'Italian_it'),
('it-IT', 'Italian_Italy_it-IT'),
('it-SM', 'Italian_San Marino_it-SM'),
('it-CH', 'Italian_Switzerland_it-CH'),
('it-VA', 'Italian_Vatican City_it-VA'),
('ja', 'Japanese_ja'),
('ja-JP', 'Japanese_Japan_ja-JP'),
('jv', 'Javanese_jv'),
('jv-Latn', 'Javanese_Latin_jv-Latn'),
('jv-Latn-ID', 'Javanese_Latin, Indonesia_jv-Latn-ID'),
('dyo', 'Jola-Fonyi_dyo'),
('dyo-SN', 'Jola-Fonyi_Senegal_dyo-SN'),
('kea', 'Kabuverdianu_kea'),
('kea-CV', 'Kabuverdianu_Cabo Verde_kea-CV'),
('kab', 'Kabyle_kab'),
('kab-DZ', 'Kabyle_Algeria_kab-DZ'),
('kkj', 'Kako_kkj'),
('kkj-CM', 'Kako_Cameroon_kkj-CM'),
('kln', 'Kalenjin_kln'),
('kln-KE', 'Kalenjin_Kenya_kln-KE'),
('kam', 'Kamba_kam'),
('kam-KE', 'Kamba_Kenya_kam-KE'),
('kn', 'Kannada_kn'),
('kn-IN', 'Kannada_India_kn-IN'),
('ks', 'Kashmiri_ks'),
('ks-Arab', 'Kashmiri_Perso-Arabic_ks-Arab'),
('ks-Arab-IN', 'Kashmiri_Perso-Arabic_ks-Arab-IN'),
('kk', 'Kazakh_kk'),
('kk-KZ', 'Kazakh_Kazakhstan_kk-KZ'),
('km', 'Khmer_km'),
('km-KH', 'Khmer_Cambodia_km-KH'),
('quc', 'K''iche_quc'),
('quc-Latn-GT', 'K''iche_Guatemala_quc-Latn-GT'),
('ki', 'Kikuyu_ki'),
('ki-KE', 'Kikuyu_Kenya_ki-KE'),
('rw', 'Kinyarwanda_rw'),
('rw-RW', 'Kinyarwanda_Rwanda_rw-RW'),
('sw', 'Kiswahili_sw'),
('sw-KE', 'Kiswahili_Kenya_sw-KE'),
('sw-TZ', 'Kiswahili_Tanzania_sw-TZ'),
('sw-UG', 'Kiswahili_Uganda_sw-UG'),
('kok', 'Konkani_kok'),
('kok-IN', 'Konkani_India_kok-IN'),
('ko', 'Korean_ko'),
('ko-KR', 'Korean_Korea_ko-KR'),
('ko-KP', 'Korean_North Korea_ko-KP'),
('khq', 'Koyra Chiini_khq'),
('khq-ML', 'Koyra Chiini_Mali_khq-ML'),
('ses', 'Koyraboro Senni_ses'),
('ses-ML', 'Koyraboro Senni_Mali_ses-ML'),
('nmg', 'Kwasio_nmg'),
('nmg-CM', 'Kwasio_Cameroon_nmg-CM'),
('ky', 'Kyrgyz_ky'),
('ky-KG', 'Kyrgyz_Kyrgyzstan_ky-KG'),
('ku-Arab-IR', 'Kurdish_Perso-Arabic, Iran_ku-Arab-IR'),
('lkt', 'Lakota_lkt'),
('lkt-US', 'Lakota_United States_lkt-US'),
('lag', 'Langi_lag'),
('lag-TZ', 'Langi_Tanzania_lag-TZ'),
('lo', 'Lao_lo'),
('lo-LA', 'Lao_Lao P.D.R._lo-LA'),
('lv', 'Latvian_lv'),
('lv-LV', 'Latvian_Latvia_lv-LV'),
('ln', 'Lingala_ln'),
('ln-AO', 'Lingala_Angola_ln-AO'),
('ln-CF', 'Lingala_Central African Republic_ln-CF'),
('ln-CG', 'Lingala_Congo_ln-CG'),
('ln-CD', 'Lingala_Congo DRC_ln-CD'),
('lt', 'Lithuanian_lt'),
('lt-LT', 'Lithuanian_Lithuania_lt-LT'),
('nds', 'Low German_nds'),
('nds-DE', 'Low German _Germany_nds-DE'),
('nds-NL', 'Low German_Netherlands_nds-NL'),
('dsb', 'Lower Sorbian_dsb'),
('dsb-DE', 'Lower Sorbian_Germany_dsb-DE'),
('lu', 'Luba-Katanga_lu'),
('lu-CD', 'Luba-Katanga_Congo DRC_lu-CD'),
('luo', 'Luo_luo'),
('luo-KE', 'Luo_Kenya_luo-KE'),
('lb', 'Luxembourgish_lb'),
('lb-LU', 'Luxembourgish_Luxembourg_lb-LU'),
('luy', 'Luyia_luy'),
('luy-KE', 'Luyia_Kenya_luy-KE'),
('mk', 'Macedonian_mk'),
('mk-MK', 'Macedonian_Macedonia (Former Yugoslav Republic of Macedonia)_mk-MK'),
('jmc', 'Machame_jmc'),
('jmc-TZ', 'Machame_Tanzania_jmc-TZ'),
('mgh', 'Makhuwa-Meetto_mgh'),
('mgh-MZ', 'Makhuwa-Meetto_Mozambique_mgh-MZ'),
('kde', 'Makonde_kde'),
('kde-TZ', 'Makonde_Tanzania_kde-TZ'),
('mg', 'Malagasy_mg'),
('mg-MG', 'Malagasy_Madagascar_mg-MG'),
('ms', 'Malay_ms'),
('ms-BN', 'Malay_Brunei Darussalam_ms-BN'),
('ms-MY', 'Malay_Malaysia_ms-MY'),
('ml', 'Malayalam_ml'),
('ml-IN', 'Malayalam_India_ml-IN'),
('mt', 'Maltese_mt'),
('mt-MT', 'Maltese_Malta_mt-MT'),
('gv', 'Manx_gv'),
('gv-IM', 'Manx_Isle of Man_gv-IM'),
('mi', 'Maori_mi'),
('mi-NZ', 'Maori_New Zealand_mi-NZ'),
('arn', 'Mapudungun_arn'),
('arn-CL', 'Mapudungun_Chile_arn-CL'),
('mr', 'Marathi_mr'),
('mr-IN', 'Marathi_India_mr-IN'),
('mas', 'Masai_mas'),
('mas-KE', 'Masai_Kenya_mas-KE'),
('mas-TZ', 'Masai_Tanzania_mas-TZ'),
('mzn-IR', 'Mazanderani_Iran_mzn-IR'),
('mer', 'Meru_mer'),
('mer-KE', 'Meru_Kenya_mer-KE'),
('mgo', 'Meta''_mgo'),
('mgo-CM', 'Meta''_Cameroon_mgo-CM'),
('moh', 'Mohawk_moh'),
('moh-CA', 'Mohawk_Canada_moh-CA'),
('mn', 'Mongolian (Cyrillic)_mn'),
('mn-Cyrl', 'Mongolian (Cyrillic)_mn-Cyrl'),
('mn-MN', 'Mongolian (Cyrillic)_Mongolia_mn-MN'),
('mn-Mong', 'Mongolian (Traditional Mongolian)_mn-Mong'),
('mn-Mong-CN', 'Mongolian (Traditional Mongolian)_People''s Republic of China_mn-Mong-CN'),
('mn-Mong-MN', 'Mongolian (Traditional Mongolian)_Mongolia_mn-Mong-MN'),
('mfe', 'Morisyen_mfe'),
('mfe-MU', 'Morisyen_Mauritius_mfe-MU'),
('mua', 'Mundang_mua'),
('mua-CM', 'Mundang_Cameroon_mua-CM'),
('nqo', 'N''ko_nqo'),
('nqo-GN', 'N''ko_Guinea_nqo-GN'),
('naq', 'Nama_naq'),
('naq-NA', 'Nama_Namibia_naq-NA'),
('ne', 'Nepali_ne'),
('ne-IN', 'Nepali_India_ne-IN'),
('ne-NP', 'Nepali_Nepal_ne-NP'),
('nnh', 'Ngiemboon_nnh'),
('nnh-CM', 'Ngiemboon_Cameroon_nnh-CM'),
('jgo', 'Ngomba_jgo'),
('jgo-CM', 'Ngomba_Cameroon_jgo-CM'),
('lrc-IQ', 'Northern Luri_Iraq_lrc-IQ'),
('lrc-IR', 'Northern Luri_Iran_lrc-IR'),
('nd', 'North Ndebele_nd'),
('nd-ZW', 'North Ndebele_Zimbabwe_nd-ZW'),
('no', 'Norwegian (Bokmal)_no'),
('nb', 'Norwegian (Bokmal)_nb'),
('nb-NO', 'Norwegian (Bokmal)_Norway_nb-NO'),
('nn', 'Norwegian (Nynorsk)_nn'),
('nn-NO', 'Norwegian (Nynorsk)_Norway_nn-NO'),
('nb-SJ', 'Norwegian Bokmål_Svalbard and Jan Mayen_nb-SJ'),
('nus', 'Nuer_nus'),
('nus-SD', 'Nuer_Sudan_nus-SD'),
('nyn', 'Nyankole_nyn'),
('nyn-UG', 'Nyankole_Uganda_nyn-UG'),
('oc', 'Occitan_oc'),
('oc-FR', 'Occitan_France_oc-FR'),
('or', 'Odia_or'),
('or-IN', 'Odia_India_or-IN'),
('om', 'Oromo_om'),
('om-ET', 'Oromo_Ethiopia_om-ET'),
('om-KE', 'Oromo_Kenya_om-KE'),
('os', 'Ossetian_os'),
('os-GE', 'Ossetian_Cyrillic, Georgia_os-GE'),
('os-RU', 'Ossetian_Cyrillic, Russia_os-RU'),
('ps', 'Pashto_ps'),
('ps-AF', 'Pashto_Afghanistan_ps-AF'),
('fa', 'Persian_fa'),
('fa-AF', 'Persian_Afghanistan_fa-AF'),
('fa-IR', 'Persian_Iran_fa-IR'),
('pl', 'Polish_pl'),
('pl-PL', 'Polish_Poland_pl-PL'),
('pt', 'Portuguese_pt'),
('pt-AO', 'Portuguese_Angola_pt-AO'),
('pt-BR', 'Portuguese_Brazil_pt-BR'),
('pt-CV', 'Portuguese_Cabo Verde_pt-CV'),
('pt-GQ', 'Portuguese_Equatorial Guinea_pt-GQ'),
('pt-GW', 'Portuguese_Guinea-Bissau_pt-GW'),
('pt-LU', 'Portuguese_Luxembourg_pt-LU'),
('pt-MO', 'Portuguese_Macao SAR_pt-MO'),
('pt-MZ', 'Portuguese_Mozambique_pt-MZ'),
('pt-PT', 'Portuguese_Portugal_pt-PT'),
('pt-ST', 'Portuguese_São Tomé and Príncipe_pt-ST'),
('pt-CH', 'Portuguese_Switzerland_pt-CH'),
('pt-TL', 'Portuguese_Timor-Leste_pt-TL'),
('prg-001', 'Prussian_prg-001'),
('pa', 'Punjabi_pa'),
('pa-Arab', 'Punjabi_pa-Arab'),
('pa-IN', 'Punjabi_India_pa-IN'),
('pa-Arab-PK', 'Punjabi_Islamic Republic of Pakistan_pa-Arab-PK'),
('quz', 'Quechua_quz'),
('quz-BO', 'Quechua_Bolivia_quz-BO'),
('quz-EC', 'Quechua_Ecuador_quz-EC'),
('quz-PE', 'Quechua_Peru_quz-PE'),
('ksh', 'Ripuarian_ksh'),
('ksh-DE', 'Ripuarian_Germany_ksh-DE'),
('ro', 'Romanian_ro'),
('ro-MD', 'Romanian_Moldova_ro-MD'),
('ro-RO', 'Romanian_Romania_ro-RO'),
('rm', 'Romansh_rm'),
('rm-CH', 'Romansh_Switzerland_rm-CH'),
('rof', 'Rombo_rof'),
('rof-TZ', 'Rombo_Tanzania_rof-TZ'),
('rn', 'Rundi_rn'),
('rn-BI', 'Rundi_Burundi_rn-BI'),
('ru', 'Russian_ru'),
('ru-BY', 'Russian_Belarus_ru-BY'),
('ru-KZ', 'Russian_Kazakhstan_ru-KZ'),
('ru-KG', 'Russian_Kyrgyzstan_ru-KG'),
('ru-MD', 'Russian_Moldova_ru-MD'),
('ru-RU', 'Russian_Russia_ru-RU'),
('ru-UA', 'Russian_Ukraine_ru-UA'),
('rwk', 'Rwa_rwk'),
('rwk-TZ', 'Rwa_Tanzania_rwk-TZ'),
('ssy', 'Saho_ssy'),
('ssy-ER', 'Saho_Eritrea_ssy-ER'),
('sah', 'Sakha_sah'),
('sah-RU', 'Sakha_Russia_sah-RU'),
('saq', 'Samburu_saq'),
('saq-KE', 'Samburu_Kenya_saq-KE'),
('smn', 'Sami (Inari)_smn'),
('smn-FI', 'Sami (Inari)_Finland_smn-FI'),
('smj', 'Sami (Lule)_smj'),
('smj-NO', 'Sami (Lule)_Norway_smj-NO'),
('smj-SE', 'Sami (Lule)_Sweden_smj-SE'),
('se', 'Sami (Northern)_se'),
('se-FI', 'Sami (Northern)_Finland_se-FI'),
('se-NO', 'Sami (Northern)_Norway_se-NO'),
('se-SE', 'Sami (Northern)_Sweden_se-SE'),
('sms', 'Sami (Skolt)_sms'),
('sms-FI', 'Sami (Skolt)_Finland_sms-FI'),
('sma', 'Sami (Southern)_sma'),
('sma-NO', 'Sami (Southern)_Norway_sma-NO'),
('sma-SE', 'Sami (Southern)_Sweden_sma-SE'),
('sg', 'Sango_sg'),
('sg-CF', 'Sango_Central African Republic_sg-CF'),
('sbp', 'Sangu_sbp'),
('sbp-TZ', 'Sangu_Tanzania_sbp-TZ'),
('sa', 'Sanskrit_sa'),
('sa-IN', 'Sanskrit_India_sa-IN'),
('gd', 'Scottish Gaelic_gd'),
('gd-GB', 'Scottish Gaelic_United Kingdom_gd-GB'),
('seh', 'Sena_seh'),
('seh-MZ', 'Sena_Mozambique_seh-MZ'),
('sr-Cyrl', 'Serbian (Cyrillic)_sr-Cyrl'),
('sr-Cyrl-BA', 'Serbian (Cyrillic)_Bosnia and Herzegovina_sr-Cyrl-BA'),
('sr-Cyrl-ME', 'Serbian (Cyrillic)_Montenegro_sr-Cyrl-ME'),
('sr-Cyrl-RS', 'Serbian (Cyrillic)_Serbia_sr-Cyrl-RS'),
('sr-Cyrl-CS', 'Serbian (Cyrillic)_Serbia and Montenegro (Former)_sr-Cyrl-CS'),
('sr-Latn', 'Serbian (Latin)_sr-Latn'),
('sr', 'Serbian (Latin)_sr'),
('sr-Latn-BA', 'Serbian (Latin)_Bosnia and Herzegovina_sr-Latn-BA'),
('sr-Latn-ME', 'Serbian (Latin)_Montenegro_sr-Latn-ME'),
('sr-Latn-RS', 'Serbian (Latin)_Serbia_sr-Latn-RS'),
('sr-Latn-CS', 'Serbian (Latin)_Serbia and Montenegro (Former)_sr-Latn-CS'),
('nso', 'Sesotho sa Leboa_nso'),
('nso-ZA', 'Sesotho sa Leboa_South Africa_nso-ZA'),
('tn', 'Setswana_tn'),
('tn-BW', 'Setswana_Botswana_tn-BW'),
('tn-ZA', 'Setswana_South Africa_tn-ZA'),
('ksb', 'Shambala_ksb'),
('ksb-TZ', 'Shambala_Tanzania_ksb-TZ'),
('sn', 'Shona_sn'),
('sn-Latn', 'Shona_Latin_sn-Latn'),
('sn-Latn-ZW', 'Shona_Zimbabwe_sn-Latn-ZW'),
('sd', 'Sindhi_sd'),
('sd-Arab', 'Sindhi_sd-Arab'),
('sd-Arab-PK', 'Sindhi_Islamic Republic of Pakistan_sd-Arab-PK'),
('si', 'Sinhala_si'),
('si-LK', 'Sinhala_Sri Lanka_si-LK'),
('sk', 'Slovak_sk'),
('sk-SK', 'Slovak_Slovakia_sk-SK'),
('sl', 'Slovenian_sl'),
('sl-SI', 'Slovenian_Slovenia_sl-SI'),
('xog', 'Soga_xog'),
('xog-UG', 'Soga_Uganda_xog-UG'),
('so', 'Somali_so'),
('so-DJ', 'Somali_Djibouti_so-DJ'),
('so-ET', 'Somali_Ethiopia_so-ET'),
('so-KE', 'Somali_Kenya_so-KE'),
('so-SO', 'Somali_Somalia_so-SO'),
('st', 'Sotho_st'),
('st-ZA', 'Sotho_South Africa_st-ZA'),
('nr', 'South Ndebele_nr'),
('nr-ZA', 'South Ndebele_South Africa_nr-ZA'),
('st-LS', 'Southern Sotho_Lesotho_st-LS'),
('es', 'Spanish_es'),
('es-AR', 'Spanish_Argentina_es-AR'),
('es-BZ', 'Spanish_Belize_es-BZ'),
('es-VE', 'Spanish_Bolivarian Republic of Venezuela_es-VE'),
('es-BO', 'Spanish_Bolivia_es-BO'),
('es-BR', 'Spanish_Brazil_es-BR'),
('es-CL', 'Spanish_Chile_es-CL'),
('es-CO', 'Spanish_Colombia_es-CO'),
('es-CR', 'Spanish_Costa Rica_es-CR'),
('es-CU', 'Spanish_Cuba_es-CU'),
('es-DO', 'Spanish_Dominican Republic_es-DO'),
('es-EC', 'Spanish_Ecuador_es-EC'),
('es-SV', 'Spanish_El Salvador_es-SV'),
('es-GQ', 'Spanish_Equatorial Guinea_es-GQ'),
('es-GT', 'Spanish_Guatemala_es-GT'),
('es-HN', 'Spanish_Honduras_es-HN'),
('es-419', 'Spanish_Latin America_es-419'),
('es-MX', 'Spanish_Mexico_es-MX'),
('es-NI', 'Spanish_Nicaragua_es-NI'),
('es-PA', 'Spanish_Panama_es-PA'),
('es-PY', 'Spanish_Paraguay_es-PY'),
('es-PE', 'Spanish_Peru_es-PE'),
('es-PH', 'Spanish_Philippines_es-PH'),
('es-PR', 'Spanish_Puerto Rico_es-PR'),
('es-ES_tradnl', 'Spanish_Spain_es-ES_tradnl'),
('es-ES', 'Spanish_Spain_es-ES'),
('es-US', 'Spanish_United States_es-US'),
('es-UY', 'Spanish_Uruguay_es-UY'),
('zgh', 'Standard Moroccan Tamazight_zgh'),
('zgh-Tfng-MA', 'Standard Moroccan Tamazight_Morocco_zgh-Tfng-MA'),
('zgh-Tfng', 'Standard Moroccan Tamazight_Tifinagh_zgh-Tfng'),
('ss', 'Swati_ss'),
('ss-ZA', 'Swati_South Africa_ss-ZA'),
('ss-SZ', 'Swati_Swaziland_ss-SZ'),
('sv', 'Swedish_sv'),
('sv-AX', 'Swedish_Åland Islands_sv-AX'),
('sv-FI', 'Swedish_Finland_sv-FI'),
('sv-SE', 'Swedish_Sweden_sv-SE'),
('syr', 'Syriac_syr'),
('syr-SY', 'Syriac_Syria_syr-SY'),
('shi', 'Tachelhit_shi'),
('shi-Tfng', 'Tachelhit_Tifinagh_shi-Tfng'),
('shi-Tfng-MA', 'Tachelhit_Tifinagh, Morocco_shi-Tfng-MA'),
('shi-Latn', 'Tachelhit (Latin)_shi-Latn'),
('shi-Latn-MA', 'Tachelhit (Latin)_Morocco_shi-Latn-MA'),
('dav', 'Taita_dav'),
('dav-KE', 'Taita_Kenya_dav-KE'),
('tg', 'Tajik (Cyrillic)_tg'),
('tg-Cyrl', 'Tajik (Cyrillic)_tg-Cyrl'),
('tg-Cyrl-TJ', 'Tajik (Cyrillic)_Tajikistan_tg-Cyrl-TJ'),
('tzm', 'Tamazight (Latin)_tzm'),
('tzm-Latn', 'Tamazight (Latin)_tzm-Latn'),
('tzm-Latn-DZ', 'Tamazight (Latin)_Algeria_tzm-Latn-DZ'),
('ta', 'Tamil_ta'),
('ta-IN', 'Tamil_India_ta-IN'),
('ta-MY', 'Tamil_Malaysia_ta-MY'),
('ta-SG', 'Tamil_Singapore_ta-SG'),
('ta-LK', 'Tamil_Sri Lanka_ta-LK'),
('twq', 'Tasawaq_twq'),
('twq-NE', 'Tasawaq_Niger_twq-NE'),
('tt', 'Tatar_tt'),
('tt-RU', 'Tatar_Russia_tt-RU'),
('te', 'Telugu_te'),
('te-IN', 'Telugu_India_te-IN'),
('teo', 'Teso_teo'),
('teo-KE', 'Teso_Kenya_teo-KE'),
('teo-UG', 'Teso_Uganda_teo-UG'),
('th', 'Thai_th'),
('th-TH', 'Thai_Thailand_th-TH'),
('bo', 'Tibetan_bo'),
('bo-IN', 'Tibetan_India_bo-IN'),
('bo-CN', 'Tibetan_People''s Republic of China_bo-CN'),
('tig', 'Tigre_tig'),
('tig-ER', 'Tigre_Eritrea_tig-ER'),
('ti', 'Tigrinya_ti'),
('ti-ER', 'Tigrinya_Eritrea_ti-ER'),
('ti-ET', 'Tigrinya_Ethiopia_ti-ET'),
('to', 'Tongan_to'),
('to-TO', 'Tongan_Tonga_to-TO'),
('ts', 'Tsonga_ts'),
('ts-ZA', 'Tsonga_South Africa_ts-ZA'),
('tr', 'Turkish_tr'),
('tr-CY', 'Turkish_Cyprus_tr-CY'),
('tr-TR', 'Turkish_Turkey_tr-TR'),
('tk', 'Turkmen_tk'),
('tk-TM', 'Turkmen_Turkmenistan_tk-TM'),
('uk', 'Ukrainian_uk'),
('uk-UA', 'Ukrainian_Ukraine_uk-UA'),
('dsb or hsb', 'Upper Sorbian_dsb or hsb'),
('hsb-DE', 'Upper Sorbian_Germany_hsb-DE'),
('ur', 'Urdu_ur'),
('ur-IN', 'Urdu_India_ur-IN'),
('ur-PK', 'Urdu_Islamic Republic of Pakistan_ur-PK'),
('ug', 'Uyghur_ug'),
('ug-CN', 'Uyghur_People''s Republic of China_ug-CN'),
('uz-Arab', 'Uzbek_Perso-Arabic_uz-Arab'),
('uz-Arab-AF', 'Uzbek_Perso-Arabic, Afghanistan_uz-Arab-AF'),
('uz-Cyrl', 'Uzbek (Cyrillic)_uz-Cyrl'),
('uz-Cyrl-UZ', 'Uzbek (Cyrillic)_Uzbekistan_uz-Cyrl-UZ'),
('uz', 'Uzbek (Latin)_uz'),
('uz-Latn', 'Uzbek (Latin)_uz-Latn'),
('uz-Latn-UZ', 'Uzbek (Latin)_Uzbekistan_uz-Latn-UZ'),
('vai', 'Vai_vai'),
('vai-Vaii', 'Vai_vai-Vaii'),
('vai-Vaii-LR', 'Vai_Liberia_vai-Vaii-LR'),
('vai-Latn-LR', 'Vai (Latin)_ Liberia_vai-Latn-LR'),
('vai-Latn', 'Vai (Latin)_vai-Latn'),
('ca-ES-valencia', 'Valencian_Spain_ca-ES-valencia'),
('ve', 'Venda_ve'),
('ve-ZA', 'Venda_South Africa_ve-ZA'),
('vi', 'Vietnamese_vi'),
('vi-VN', 'Vietnamese_Vietnam_vi-VN'),
('vo', 'Volapük_vo'),
('vo-001', 'Volapük_World_vo-001'),
('vun', 'Vunjo_vun'),
('vun-TZ', 'Vunjo_Tanzania_vun-TZ'),
('wae', 'Walser_wae'),
('wae-CH', 'Walser_Switzerland_wae-CH'),
('cy', 'Welsh_cy'),
('cy-GB', 'Welsh_United Kingdom_cy-GB'),
('wal', 'Wolaytta_wal'),
('wal-ET', 'Wolaytta_Ethiopia_wal-ET'),
('wo', 'Wolof_wo'),
('wo-SN', 'Wolof_Senegal_wo-SN'),
('xh', 'Xhosa_xh'),
('xh-ZA', 'Xhosa_South Africa_xh-ZA'),
('yav', 'Yangben_yav'),
('yav-CM', 'Yangben_Cameroon_yav-CM'),
('ii', 'Yi_ii'),
('ii-CN', 'Yi_People''s Republic of China_ii-CN'),
('yo', 'Yoruba_yo'),
('yo-BJ', 'Yoruba_Benin_yo-BJ'),
('yo-NG', 'Yoruba_Nigeria_yo-NG'),
('dje', 'Zarma_dje'),
('dje-NE', 'Zarma_Niger_dje-NE'),
('zu', 'Zulu_zu'),
('zu-ZA', 'Zulu_South Africa_zu-ZA')


-- including Nvarchar

INSERT [dbo].[vts_tbMultiLanguage] ([LanguageCode], [LanguageDescription]) VALUES
(N'aa', N'Afar_aa'),
(N'aa-DJ', N'Afar_Djibouti_aa-DJ'),
(N'aa-ER', N'Afar_Eritrea_aa-ER'),
(N'aa-ET', N'Afar_Ethiopia_aa-ET'),
(N'af', N'Afrikaans_af'),
(N'af-NA', N'Afrikaans_Namibia_af-NA'),
(N'af-ZA', N'Afrikaans_South Africa_af-ZA'),
(N'agq', N'Aghem_agq'),
(N'agq-CM', N'Aghem_Cameroon_agq-CM'),
(N'ak', N'Akan_ak'),
(N'ak-GH', N'Akan_Ghana_ak-GH'),
(N'sq', N'Albanian_sq'),
(N'sq-AL', N'Albanian_Albania_sq-AL'),
(N'sq-MK', N'Albanian_Macedonia, FYRO_sq-MK'),
(N'gsw', N'Alsatian_gsw'),
(N'gsw-FR', N'Alsatian_France_gsw-FR'),
(N'gsw-LI', N'Alsatian_Liechtenstein_gsw-LI'),
(N'gsw-CH', N'Alsatian_Switzerland_gsw-CH'),
(N'am', N'Amharic_am'),
(N'am-ET', N'Amharic_Ethiopia_am-ET'),
(N'ar', N'Arabic_ar'),
(N'ar-DZ', N'Arabic_Algeria_ar-DZ'),
(N'ar-BH', N'Arabic_Bahrain_ar-BH'),
(N'ar-TD', N'Arabic_Chad_ar-TD'),
(N'ar-KM', N'Arabic_Comoros_ar-KM'),
(N'ar-DJ', N'Arabic_Djibouti_ar-DJ'),
(N'ar-EG', N'Arabic_Egypt_ar-EG'),
(N'ar-ER', N'Arabic_Eritrea_ar-ER'),
(N'ar-IQ', N'Arabic_Iraq_ar-IQ'),
(N'ar-IL', N'Arabic_Israel_ar-IL'),
(N'ar-JO', N'Arabic_Jordan_ar-JO'),
(N'ar-KW', N'Arabic_Kuwait_ar-KW'),
(N'ar-LB', N'Arabic_Lebanon_ar-LB'),
(N'ar-LY', N'Arabic_Libya_ar-LY'),
(N'ar-MR', N'Arabic_Mauritania_ar-MR'),
(N'ar-MA', N'Arabic_Morocco_ar-MA'),
(N'ar-OM', N'Arabic_Oman_ar-OM'),
(N'ar-PS', N'Arabic_Palestinian Authority_ar-PS'),
(N'ar-QA', N'Arabic_Qatar_ar-QA'),
(N'ar-SA', N'Arabic_Saudi Arabia_ar-SA'),
(N'ar-SO', N'Arabic_Somalia_ar-SO'),
(N'ar-SS', N'Arabic_South Sudan_ar-SS'),
(N'ar-SD', N'Arabic_Sudan_ar-SD'),
(N'ar-SY', N'Arabic_Syria_ar-SY'),
(N'ar-TN', N'Arabic_Tunisia_ar-TN'),
(N'ar-AE', N'Arabic_U.A.E._ar-AE'),
(N'ar-001', N'Arabic_World_ar-001'),
(N'ar-YE', N'Arabic_Yemen_ar-YE'),
(N'hy', N'Armenian_hy'),
(N'hy-AM', N'Armenian_Armenia_hy-AM'),
(N'as', N'Assamese_as'),
(N'as-IN', N'Assamese_India_as-IN'),
(N'ast', N'Asturian_ast'),
(N'ast-ES', N'Asturian_Spain_ast-ES'),
(N'asa', N'Asu_asa'),
(N'asa-TZ', N'Asu_Tanzania_asa-TZ'),
(N'az-Cyrl', N'Azerbaijani (Cyrillic)_az-Cyrl'),
(N'az-Cyrl-AZ', N'Azerbaijani (Cyrillic)_Azerbaijan_az-Cyrl-AZ'),
(N'az', N'Azerbaijani (Latin)_az'),
(N'az-Latn', N'Azerbaijani (Latin)_az-Latn'),
(N'az-Latn-AZ', N'Azerbaijani (Latin)_Azerbaijan_az-Latn-AZ'),
(N'ksf', N'Bafia_ksf'),
(N'ksf-CM', N'Bafia_Cameroon_ksf-CM'),
(N'bm', N'Bamanankan_bm'),
(N'bm-Latn-ML', N'Bamanankan (Latin)_Mali_bm-Latn-ML'),
(N'bn', N'Bangla_bn'),
(N'bn-BD', N'Bangla_Bangladesh_bn-BD'),
(N'bn-IN', N'Bangla_India_bn-IN'),
(N'bas', N'Basaa_bas'),
(N'bas-CM', N'Basaa_Cameroon_bas-CM'),
(N'ba', N'Bashkir_ba'),
(N'ba-RU', N'Bashkir_Russia_ba-RU'),
(N'eu', N'Basque_eu'),
(N'eu-ES', N'Basque_Spain_eu-ES'),
(N'be', N'Belarusian_be'),
(N'be-BY', N'Belarusian_Belarus_be-BY'),
(N'bem', N'Bemba_bem'),
(N'bem-ZM', N'Bemba_Zambia_bem-ZM'),
(N'bez', N'Bena_bez'),
(N'bez-TZ', N'Bena_Tanzania_bez-TZ'),
(N'byn', N'Blin_byn'),
(N'byn-ER', N'Blin_Eritrea_byn-ER'),
(N'brx', N'Bodo_brx'),
(N'brx-IN', N'Bodo_India_brx-IN'),
(N'bs-Cyrl', N'Bosnian (Cyrillic)_bs-Cyrl'),
(N'bs-Cyrl-BA', N'Bosnian (Cyrillic)_Bosnia and Herzegovina_bs-Cyrl-BA'),
(N'bs-Latn', N'Bosnian (Latin)_bs-Latn'),
(N'bs', N'Bosnian (Latin)_bs'),
(N'bs-Latn-BA', N'Bosnian (Latin)_Bosnia and Herzegovina_bs-Latn-BA'),
(N'br', N'Breton_br'),
(N'br-FR', N'Breton_France_br-FR'),
(N'bg', N'Bulgarian_bg'),
(N'bg-BG', N'Bulgarian_Bulgaria_bg-BG'),
(N'my', N'Burmese_my'),
(N'my-MM', N'Burmese_Myanmar_my-MM'),
(N'ca', N'Catalan_ca'),
(N'ca-AD', N'Catalan_Andorra_ca-AD'),
(N'ca-FR', N'Catalan_France_ca-FR'),
(N'ca-IT', N'Catalan_Italy_ca-IT'),
(N'ca-ES', N'Catalan_Spain_ca-ES'),
(N'tzm-Latn-MA', N'Central Atlas Tamazight (Latin)_Morocco_tzm-Latn-MA'),
(N'ku', N'Central Kurdish_ku'),
(N'ku-Arab', N'Central Kurdish_ku-Arab'),
(N'ku-Arab-IQ', N'Central Kurdish_Iraq_ku-Arab-IQ'),
(N'cd-RU', N'Chechen_Russia_cd-RU'),
(N'chr', N'Cherokee_chr'),
(N'chr-Cher', N'Cherokee_chr-Cher'),
(N'chr-Cher-US', N'Cherokee_United States_chr-Cher-US'),
(N'cgg', N'Chiga_cgg'),
(N'cgg-UG', N'Chiga_Uganda_cgg-UG'),
(N'zh-Hans', N'Chinese (Simplified)_zh-Hans'),
(N'zh', N'Chinese (Simplified)_zh'),
(N'zh-CN', N'Chinese (Simplified)_People''s Republic of China_zh-CN'),
(N'zh-SG', N'Chinese (Simplified)_Singapore_zh-SG'),
(N'zh-Hant', N'Chinese (Traditional)_zh-Hant'),
(N'zh-HK', N'Chinese (Traditional)_Hong Kong S.A.R._zh-HK'),
(N'zh-MO', N'Chinese (Traditional)_Macao S.A.R._zh-MO'),
(N'zh-TW', N'Chinese (Traditional)_Taiwan_zh-TW'),
(N'cu-RU', N'Church Slavic_Russia_cu-RU'),
(N'swc', N'Congo Swahili_swc'),
(N'swc-CD', N'Congo Swahili_Congo DRC_swc-CD'),
(N'kw', N'Cornish_kw'),
(N'kw-GB', N'Cornish_United Kingdom_kw-GB'),
(N'co', N'Corsican_co'),
(N'co-FR', N'Corsican_France_co-FR'),
(N'bs, hr, or sr', N'Croatian_bs, hr, or sr'),
(N'hr-HR', N'Croatian_Croatia_hr-HR'),
(N'hr-BA', N'Croatian (Latin)_Bosnia and Herzegovina_hr-BA'),
(N'cs', N'Czech_cs'),
(N'cs-CZ', N'Czech_Czech Republic_cs-CZ'),
(N'da', N'Danish_da'),
(N'da-DK', N'Danish_Denmark_da-DK'),
(N'da-GL', N'Danish_Greenland_da-GL'),
(N'prs', N'Dari_prs'),
(N'prs-AF', N'Dari_Afghanistan_prs-AF'),
(N'dv', N'Divehi_dv'),
(N'dv-MV', N'Divehi_Maldives_dv-MV'),
(N'dua', N'Duala_dua'),
(N'dua-CM', N'Duala_Cameroon_dua-CM'),
(N'nl', N'Dutch_nl'),
(N'nl-AW', N'Dutch_Aruba_nl-AW'),
(N'nl-BE', N'Dutch_Belgium_nl-BE'),
(N'nl-BQ', N'Dutch_Bonaire, Sint Eustatius and Saba_nl-BQ'),
(N'nl-CW', N'Dutch_Curaçao_nl-CW'),
(N'nl-NL', N'Dutch_Netherlands_nl-NL'),
(N'nl-SX', N'Dutch_Sint Maarten_nl-SX'),
(N'nl-SR', N'Dutch_Suriname_nl-SR'),
(N'dz', N'Dzongkha_dz'),
(N'dz-BT', N'Dzongkha_Bhutan_dz-BT'),
(N'ebu', N'Embu_ebu'),
(N'ebu-KE', N'Embu_Kenya_ebu-KE'),
(N'en', N'English_en'),
(N'en-AS', N'English_American Samoa_en-AS'),
(N'en-AI', N'English_Anguilla_en-AI'),
(N'en-AG', N'English_Antigua and Barbuda_en-AG'),
(N'en-AU', N'English_Australia_en-AU'),
(N'en-AT', N'English_Austria_en-AT'),
(N'en-BS', N'English_Bahamas_en-BS'),
(N'en-BB', N'English_Barbados_en-BB'),
(N'en-BE', N'English_Belgium_en-BE'),
(N'en-BZ', N'English_Belize_en-BZ'),
(N'en-BM', N'English_Bermuda_en-BM'),
(N'en-BW', N'English_Botswana_en-BW'),
(N'en-IO', N'English_British Indian Ocean Territory_en-IO'),
(N'en-VG', N'English_British Virgin Islands_en-VG'),
(N'en-BI', N'English_Burundi_en-BI'),
(N'en-CM', N'English_Cameroon_en-CM'),
(N'en-CA', N'English_Canada_en-CA'),
(N'en-029', N'English_Caribbean_en-029'),
(N'en-KY', N'English_Cayman Islands_en-KY'),
(N'en-CX', N'English_Christmas Island_en-CX'),
(N'en-CC', N'English_Cocos [Keeling] Islands_en-CC'),
(N'en-CK', N'English_Cook Islands_en-CK'),
(N'en-CY', N'English_Cyprus_en-CY'),
(N'en-DK', N'English_Denmark_en-DK'),
(N'en-DM', N'English_Dominica_en-DM'),
(N'en-ER', N'English_Eritrea_en-ER'),
(N'en-150', N'English_Europe_en-150'),
(N'en-FK', N'English_Falkland Islands_en-FK'),
(N'en-FI', N'English_Finland_en-FI'),
(N'en-FJ', N'English_Fiji_en-FJ'),
(N'en-GM', N'English_Gambia_en-GM'),
(N'en-DE', N'English_Germany_en-DE'),
(N'en-GH', N'English_Ghana_en-GH'),
(N'en-GI', N'English_Gibraltar_en-GI'),
(N'en-GD', N'English_Grenada_en-GD'),
(N'en-GU', N'English_Guam_en-GU'),
(N'en-GG', N'English_Guernsey_en-GG'),
(N'en-GY', N'English_Guyana_en-GY'),
(N'en-HK', N'English_Hong Kong_en-HK'),
(N'en-IN', N'English_India_en-IN'),
(N'en-IE', N'English_Ireland_en-IE'),
(N'en-IM', N'English_Isle of Man_en-IM'),
(N'en-IL', N'English_Israel_en-IL'),
(N'en-JM', N'English_Jamaica_en-JM'),
(N'en-JE', N'English_Jersey_en-JE'),
(N'en-KE', N'English_Kenya_en-KE'),
(N'en-KI', N'English_Kiribati_en-KI'),
(N'en-LS', N'English_Lesotho_en-LS'),
(N'en-LR', N'English_Liberia_en-LR'),
(N'en-MO', N'English_Macao SAR_en-MO'),
(N'en-MG', N'English_Madagascar_en-MG'),
(N'en-MW', N'English_Malawi_en-MW'),
(N'en-MY', N'English_Malaysia_en-MY'),
(N'en-MT', N'English_Malta_en-MT'),
(N'en-MH', N'English_Marshall Islands_en-MH'),
(N'en-MU', N'English_Mauritius_en-MU'),
(N'en-FM', N'English_Micronesia_en-FM'),
(N'en-MS', N'English_Montserrat_en-MS'),
(N'en-NA', N'English_Namibia_en-NA'),
(N'en-NR', N'English_Nauru_en-NR'),
(N'en-NL', N'English_Netherlands_en-NL'),
(N'en-NZ', N'English_New Zealand_en-NZ'),
(N'en-NG', N'English_Nigeria_en-NG'),
(N'en-NU', N'English_Niue_en-NU'),
(N'en-NF', N'English_Norfolk Island_en-NF'),
(N'en-MP', N'English_Northern Mariana Islands_en-MP'),
(N'en-PK', N'English_Pakistan_en-PK'),
(N'en-PW', N'English_Palau_en-PW'),
(N'en-PG', N'English_Papua New Guinea_en-PG'),
(N'en-PN', N'English_Pitcairn Islands_en-PN'),
(N'en-PR', N'English_Puerto Rico_en-PR'),
(N'en-PH', N'English_Republic of the Philippines_en-PH'),
(N'en-RW', N'English_Rwanda_en-RW'),
(N'en-KN', N'English_Saint Kitts and Nevis_en-KN'),
(N'en-LC', N'English_Saint Lucia_en-LC'),
(N'en-VC', N'English_Saint Vincent and the Grenadines_en-VC'),
(N'en-WS', N'English_Samoa_en-WS'),
(N'en-SC', N'English_Seychelles_en-SC'),
(N'en-SL', N'English_Sierra Leone_en-SL'),
(N'en-SG', N'English_Singapore_en-SG'),
(N'en-SX', N'English_Sint Maarten_en-SX'),
(N'en-SI', N'English_Slovenia_en-SI'),
(N'en-SB', N'English_Solomon Islands_en-SB'),
(N'en-ZA', N'English_South Africa_en-ZA'),
(N'en-SS', N'English_South Sudan_en-SS'),
(N'en-SH', N'English_St Helena, Ascension, Tristan da Cunha_en-SH'),
(N'en-SD', N'English_Sudan_en-SD'),
(N'en-SZ', N'English_Swaziland_en-SZ'),
(N'en-SE', N'English_Sweden_en-SE'),
(N'en-CH', N'English_Switzerland_en-CH'),
(N'en-TZ', N'English_Tanzania_en-TZ'),
(N'en-TK', N'English_Tokelau_en-TK'),
(N'en-TO', N'English_Tonga_en-TO'),
(N'en-TT', N'English_Trinidad and Tobago_en-TT'),
(N'en-TC', N'English_Turks and Caicos Islands_en-TC'),
(N'en-TV', N'English_Tuvalu_en-TV'),
(N'en-UG', N'English_Uganda_en-UG'),
(N'en-GB', N'English_United Kingdom_en-GB'),
(N'en-US', N'English_United States_en-US'),
(N'en-UM', N'English_US Minor Outlying Islands_en-UM'),
(N'en-VI', N'English_US Virgin Islands_en-VI'),
(N'en-VU', N'English_Vanuatu_en-VU'),
(N'en-001', N'English_World_en-001'),
(N'en-ZM', N'English_Zambia_en-ZM'),
(N'en-ZW', N'English_Zimbabwe_en-ZW'),
(N'eo', N'Esperanto_eo'),
(N'eo-001', N'Esperanto_World_eo-001'),
(N'et', N'Estonian_et'),
(N'et-EE', N'Estonian_Estonia_et-EE'),
(N'ee', N'Ewe_ee'),
(N'ee-GH', N'Ewe_Ghana_ee-GH'),
(N'ee-TG', N'Ewe_Togo_ee-TG'),
(N'ewo', N'Ewondo_ewo'),
(N'ewo-CM', N'Ewondo_Cameroon_ewo-CM'),
(N'fo', N'Faroese_fo'),
(N'fo-DK', N'Faroese_Denmark_fo-DK'),
(N'fo-FO', N'Faroese_Faroe Islands_fo-FO'),
(N'fil', N'Filipino_fil'),
(N'fil-PH', N'Filipino_Philippines_fil-PH'),
(N'fi', N'Finnish_fi'),
(N'fi-FI', N'Finnish_Finland_fi-FI'),
(N'fr', N'French_fr'),
(N'fr-DZ', N'French_Algeria_fr-DZ'),
(N'fr-BE', N'French_Belgium_fr-BE'),
(N'fr-BJ', N'French_Benin_fr-BJ'),
(N'fr-BF', N'French_Burkina Faso_fr-BF'),
(N'fr-BI', N'French_Burundi_fr-BI'),
(N'fr-CM', N'French_Cameroon_fr-CM'),
(N'fr-CA', N'French_Canada_fr-CA'),
(N'fr-CF', N'French_Central African Republic_fr-CF'),
(N'fr-TD', N'French_Chad_fr-TD'),
(N'fr-KM', N'French_Comoros_fr-KM'),
(N'fr-CG', N'French_Congo_fr-CG'),
(N'fr-CD', N'French_Congo, DRC_fr-CD'),
(N'fr-CI', N'French_Côte d''Ivoire_fr-CI'),
(N'fr-DJ', N'French_Djibouti_fr-DJ'),
(N'fr-GQ', N'French_Equatorial Guinea_fr-GQ'),
(N'fr-FR', N'French_France_fr-FR'),
(N'fr-GF', N'French_French Guiana_fr-GF'),
(N'fr-PF', N'French_French Polynesia_fr-PF'),
(N'fr-GA', N'French_Gabon_fr-GA'),
(N'fr-GP', N'French_Guadeloupe_fr-GP'),
(N'fr-GN', N'French_Guinea_fr-GN'),
(N'fr-HT', N'French_Haiti_fr-HT'),
(N'fr-LU', N'French_Luxembourg_fr-LU'),
(N'fr-MG', N'French_Madagascar_fr-MG'),
(N'fr-ML', N'French_Mali_fr-ML'),
(N'fr-MQ', N'French_Martinique_fr-MQ'),
(N'fr-MR', N'French_Mauritania_fr-MR'),
(N'fr-MU', N'French_Mauritius_fr-MU'),
(N'fr-YT', N'French_Mayotte_fr-YT'),
(N'fr-MA', N'French_Morocco_fr-MA'),
(N'fr-NC', N'French_New Caledonia_fr-NC'),
(N'fr-NE', N'French_Niger_fr-NE'),
(N'fr-MC', N'French_Principality of Monaco_fr-MC'),
(N'fr-RE', N'French_Reunion_fr-RE'),
(N'fr-RW', N'French_Rwanda_fr-RW'),
(N'fr-BL', N'French_Saint Barthélemy_fr-BL'),
(N'fr-MF', N'French_Saint Martin_fr-MF'),
(N'fr-PM', N'French_Saint Pierre and Miquelon_fr-PM'),
(N'fr-SN', N'French_Senegal_fr-SN'),
(N'fr-SC', N'French_Seychelles_fr-SC'),
(N'fr-CH', N'French_Switzerland_fr-CH'),
(N'fr-SY', N'French_Syria_fr-SY'),
(N'fr-TG', N'French_Togo_fr-TG'),
(N'fr-TN', N'French_Tunisia_fr-TN'),
(N'fr-VU', N'French_Vanuatu_fr-VU'),
(N'fr-WF', N'French_Wallis and Futuna_fr-WF'),
(N'fy', N'Frisian_Frisland_fy'),
(N'fy-NL', N'Frisian_Netherlands_fy-NL'),
(N'fur', N'Friulian_fur'),
(N'fur-IT', N'Friulian_Italy_fur-IT'),
(N'ff', N'Fulah_ff'),
(N'ff-Latn', N'Fulah_ff-Latn'),
(N'ff-CM', N'Fulah_Cameroon_ff-CM'),
(N'ff-GN', N'Fulah_Guinea_ff-GN'),
(N'ff-MR', N'Fulah_Mauritania_ff-MR'),
(N'ff-Latn-SN', N'Fulah_Senegal_ff-Latn-SN'),
(N'gl', N'Galician_gl'),
(N'gl-ES', N'Galician_Spain_gl-ES'),
(N'lg', N'Ganda_lg'),
(N'lg-UG', N'Ganda_Uganda_lg-UG'),
(N'ka', N'Georgian_ka'),
(N'ka-GE', N'Georgian_Georgia_ka-GE'),
(N'de', N'German_de'),
(N'de-AT', N'German_Austria_de-AT'),
(N'de-BE', N'German_Belgium_de-BE'),
(N'de-DE', N'German_Germany_de-DE'),
(N'de-IT', N'German_Italy_de-IT'),
(N'de-LI', N'German_Liechtenstein_de-LI'),
(N'de-LU', N'German_Luxembourg_de-LU'),
(N'de-CH', N'German_Switzerland_de-CH'),
(N'el', N'Greek_el'),
(N'el-CY', N'Greek_Cyprus_el-CY'),
(N'el-GR', N'Greek_Greece_el-GR'),
(N'kl', N'Greenlandic_kl'),
(N'kl-GL', N'Greenlandic_Greenland_kl-GL'),
(N'gn', N'Guarani_gn'),
(N'gn-PY', N'Guarani_Paraguay_gn-PY'),
(N'gu', N'Gujarati_gu'),
(N'gu-IN', N'Gujarati_India_gu-IN'),
(N'guz', N'Gusii_guz'),
(N'guz-KE', N'Gusii_Kenya_guz-KE'),
(N'ha', N'Hausa (Latin)_ha'),
(N'ha-Latn', N'Hausa (Latin)_ha-Latn'),
(N'ha-Latn-GH', N'Hausa (Latin)_Ghana_ha-Latn-GH'),
(N'ha-Latn-NE', N'Hausa (Latin)_Niger_ha-Latn-NE'),
(N'ha-Latn-NG', N'Hausa (Latin)_Nigeria_ha-Latn-NG'),
(N'haw', N'Hawaiian_haw'),
(N'haw-US', N'Hawaiian_United States_haw-US'),
(N'he', N'Hebrew_he'),
(N'he-IL', N'Hebrew_Israel_he-IL'),
(N'hi', N'Hindi_hi'),
(N'hi-IN', N'Hindi_India_hi-IN'),
(N'hu', N'Hungarian_hu'),
(N'hu-HU', N'Hungarian_Hungary_hu-HU'),
(N'is', N'Icelandic_is'),
(N'is-IS', N'Icelandic_Iceland_is-IS'),
(N'ig', N'Igbo_ig'),
(N'ig-NG', N'Igbo_Nigeria_ig-NG'),
(N'id', N'Indonesian_id'),
(N'id-ID', N'Indonesian_Indonesia_id-ID'),
(N'ia', N'Interlingua_ia'),
(N'ia-FR', N'Interlingua_France_ia-FR'),
(N'ia-001', N'Interlingua_World_ia-001'),
(N'iu', N'Inuktitut (Latin)_iu'),
(N'iu-Latn', N'Inuktitut (Latin)_iu-Latn'),
(N'iu-Latn-CA', N'Inuktitut (Latin)_Canada_iu-Latn-CA'),
(N'iu-Cans', N'Inuktitut (Syllabics)_iu-Cans'),
(N'iu-Cans-CA', N'Inuktitut (Syllabics)_Canada_iu-Cans-CA'),
(N'ga', N'Irish_ga'),
(N'ga-IE', N'Irish_Ireland_ga-IE'),
(N'it', N'Italian_it'),
(N'it-IT', N'Italian_Italy_it-IT'),
(N'it-SM', N'Italian_San Marino_it-SM'),
(N'it-CH', N'Italian_Switzerland_it-CH'),
(N'it-VA', N'Italian_Vatican City_it-VA'),
(N'ja', N'Japanese_ja'),
(N'ja-JP', N'Japanese_Japan_ja-JP'),
(N'jv', N'Javanese_jv'),
(N'jv-Latn', N'Javanese_Latin_jv-Latn'),
(N'jv-Latn-ID', N'Javanese_Latin, Indonesia_jv-Latn-ID'),
(N'dyo', N'Jola-Fonyi_dyo'),
(N'dyo-SN', N'Jola-Fonyi_Senegal_dyo-SN'),
(N'kea', N'Kabuverdianu_kea'),
(N'kea-CV', N'Kabuverdianu_Cabo Verde_kea-CV'),
(N'kab', N'Kabyle_kab'),
(N'kab-DZ', N'Kabyle_Algeria_kab-DZ'),
(N'kkj', N'Kako_kkj'),
(N'kkj-CM', N'Kako_Cameroon_kkj-CM'),
(N'kln', N'Kalenjin_kln'),
(N'kln-KE', N'Kalenjin_Kenya_kln-KE'),
(N'kam', N'Kamba_kam'),
(N'kam-KE', N'Kamba_Kenya_kam-KE'),
(N'kn', N'Kannada_kn'),
(N'kn-IN', N'Kannada_India_kn-IN'),
(N'ks', N'Kashmiri_ks'),
(N'ks-Arab', N'Kashmiri_Perso-Arabic_ks-Arab'),
(N'ks-Arab-IN', N'Kashmiri_Perso-Arabic_ks-Arab-IN'),
(N'kk', N'Kazakh_kk'),
(N'kk-KZ', N'Kazakh_Kazakhstan_kk-KZ'),
(N'km', N'Khmer_km'),
(N'km-KH', N'Khmer_Cambodia_km-KH'),
(N'quc', N'K''iche_quc'),
(N'quc-Latn-GT', N'K''iche_Guatemala_quc-Latn-GT'),
(N'ki', N'Kikuyu_ki'),
(N'ki-KE', N'Kikuyu_Kenya_ki-KE'),
(N'rw', N'Kinyarwanda_rw'),
(N'rw-RW', N'Kinyarwanda_Rwanda_rw-RW'),
(N'sw', N'Kiswahili_sw'),
(N'sw-KE', N'Kiswahili_Kenya_sw-KE'),
(N'sw-TZ', N'Kiswahili_Tanzania_sw-TZ'),
(N'sw-UG', N'Kiswahili_Uganda_sw-UG'),
(N'kok', N'Konkani_kok'),
(N'kok-IN', N'Konkani_India_kok-IN'),
(N'ko', N'Korean_ko'),
(N'ko-KR', N'Korean_Korea_ko-KR'),
(N'ko-KP', N'Korean_North Korea_ko-KP'),
(N'khq', N'Koyra Chiini_khq'),
(N'khq-ML', N'Koyra Chiini_Mali_khq-ML'),
(N'ses', N'Koyraboro Senni_ses'),
(N'ses-ML', N'Koyraboro Senni_Mali_ses-ML'),
(N'nmg', N'Kwasio_nmg'),
(N'nmg-CM', N'Kwasio_Cameroon_nmg-CM'),
(N'ky', N'Kyrgyz_ky'),
(N'ky-KG', N'Kyrgyz_Kyrgyzstan_ky-KG'),
(N'ku-Arab-IR', N'Kurdish_Perso-Arabic, Iran_ku-Arab-IR'),
(N'lkt', N'Lakota_lkt'),
(N'lkt-US', N'Lakota_United States_lkt-US'),
(N'lag', N'Langi_lag'),
(N'lag-TZ', N'Langi_Tanzania_lag-TZ'),
(N'lo', N'Lao_lo'),
(N'lo-LA', N'Lao_Lao P.D.R._lo-LA'),
(N'lv', N'Latvian_lv'),
(N'lv-LV', N'Latvian_Latvia_lv-LV'),
(N'ln', N'Lingala_ln'),
(N'ln-AO', N'Lingala_Angola_ln-AO'),
(N'ln-CF', N'Lingala_Central African Republic_ln-CF'),
(N'ln-CG', N'Lingala_Congo_ln-CG'),
(N'ln-CD', N'Lingala_Congo DRC_ln-CD'),
(N'lt', N'Lithuanian_lt'),
(N'lt-LT', N'Lithuanian_Lithuania_lt-LT'),
(N'nds', N'Low German_nds'),
(N'nds-DE', N'Low German _Germany_nds-DE'),
(N'nds-NL', N'Low German_Netherlands_nds-NL'),
(N'dsb', N'Lower Sorbian_dsb'),
(N'dsb-DE', N'Lower Sorbian_Germany_dsb-DE'),
(N'lu', N'Luba-Katanga_lu'),
(N'lu-CD', N'Luba-Katanga_Congo DRC_lu-CD'),
(N'luo', N'Luo_luo'),
(N'luo-KE', N'Luo_Kenya_luo-KE'),
(N'lb', N'Luxembourgish_lb'),
(N'lb-LU', N'Luxembourgish_Luxembourg_lb-LU'),
(N'luy', N'Luyia_luy'),
(N'luy-KE', N'Luyia_Kenya_luy-KE'),
(N'mk', N'Macedonian_mk'),
(N'mk-MK', N'Macedonian_Macedonia (Former Yugoslav Republic of Macedonia)_mk-MK'),
(N'jmc', N'Machame_jmc'),
(N'jmc-TZ', N'Machame_Tanzania_jmc-TZ'),
(N'mgh', N'Makhuwa-Meetto_mgh'),
(N'mgh-MZ', N'Makhuwa-Meetto_Mozambique_mgh-MZ'),
(N'kde', N'Makonde_kde'),
(N'kde-TZ', N'Makonde_Tanzania_kde-TZ'),
(N'mg', N'Malagasy_mg'),
(N'mg-MG', N'Malagasy_Madagascar_mg-MG'),
(N'ms', N'Malay_ms'),
(N'ms-BN', N'Malay_Brunei Darussalam_ms-BN'),
(N'ms-MY', N'Malay_Malaysia_ms-MY'),
(N'ml', N'Malayalam_ml'),
(N'ml-IN', N'Malayalam_India_ml-IN'),
(N'mt', N'Maltese_mt'),
(N'mt-MT', N'Maltese_Malta_mt-MT'),
(N'gv', N'Manx_gv'),
(N'gv-IM', N'Manx_Isle of Man_gv-IM'),
(N'mi', N'Maori_mi'),
(N'mi-NZ', N'Maori_New Zealand_mi-NZ'),
(N'arn', N'Mapudungun_arn'),
(N'arn-CL', N'Mapudungun_Chile_arn-CL'),
(N'mr', N'Marathi_mr'),
(N'mr-IN', N'Marathi_India_mr-IN'),
(N'mas', N'Masai_mas'),
(N'mas-KE', N'Masai_Kenya_mas-KE'),
(N'mas-TZ', N'Masai_Tanzania_mas-TZ'),
(N'mzn-IR', N'Mazanderani_Iran_mzn-IR'),
(N'mer', N'Meru_mer'),
(N'mer-KE', N'Meru_Kenya_mer-KE'),
(N'mgo', N'Meta''_mgo'),
(N'mgo-CM', N'Meta''_Cameroon_mgo-CM'),
(N'moh', N'Mohawk_moh'),
(N'moh-CA', N'Mohawk_Canada_moh-CA'),
(N'mn', N'Mongolian (Cyrillic)_mn'),
(N'mn-Cyrl', N'Mongolian (Cyrillic)_mn-Cyrl'),
(N'mn-MN', N'Mongolian (Cyrillic)_Mongolia_mn-MN'),
(N'mn-Mong', N'Mongolian (Traditional Mongolian)_mn-Mong'),
(N'mn-Mong-CN', N'Mongolian (Traditional Mongolian)_People''s Republic of China_mn-Mong-CN'),
(N'mn-Mong-MN', N'Mongolian (Traditional Mongolian)_Mongolia_mn-Mong-MN'),
(N'mfe', N'Morisyen_mfe'),
(N'mfe-MU', N'Morisyen_Mauritius_mfe-MU'),
(N'mua', N'Mundang_mua'),
(N'mua-CM', N'Mundang_Cameroon_mua-CM'),
(N'nqo', N'N''ko_nqo'),
(N'nqo-GN', N'N''ko_Guinea_nqo-GN'),
(N'naq', N'Nama_naq'),
(N'naq-NA', N'Nama_Namibia_naq-NA'),
(N'ne', N'Nepali_ne'),
(N'ne-IN', N'Nepali_India_ne-IN'),
(N'ne-NP', N'Nepali_Nepal_ne-NP'),
(N'nnh', N'Ngiemboon_nnh'),
(N'nnh-CM', N'Ngiemboon_Cameroon_nnh-CM'),
(N'jgo', N'Ngomba_jgo'),
(N'jgo-CM', N'Ngomba_Cameroon_jgo-CM'),
(N'lrc-IQ', N'Northern Luri_Iraq_lrc-IQ'),
(N'lrc-IR', N'Northern Luri_Iran_lrc-IR'),
(N'nd', N'North Ndebele_nd'),
(N'nd-ZW', N'North Ndebele_Zimbabwe_nd-ZW'),
(N'no', N'Norwegian (Bokmal)_no'),
(N'nb', N'Norwegian (Bokmal)_nb'),
(N'nb-NO', N'Norwegian (Bokmal)_Norway_nb-NO'),
(N'nn', N'Norwegian (Nynorsk)_nn'),
(N'nn-NO', N'Norwegian (Nynorsk)_Norway_nn-NO'),
(N'nb-SJ', N'Norwegian Bokmål_Svalbard and Jan Mayen_nb-SJ'),
(N'nus', N'Nuer_nus'),
(N'nus-SD', N'Nuer_Sudan_nus-SD'),
(N'nyn', N'Nyankole_nyn'),
(N'nyn-UG', N'Nyankole_Uganda_nyn-UG'),
(N'oc', N'Occitan_oc'),
(N'oc-FR', N'Occitan_France_oc-FR'),
(N'or', N'Odia_or'),
(N'or-IN', N'Odia_India_or-IN'),
(N'om', N'Oromo_om'),
(N'om-ET', N'Oromo_Ethiopia_om-ET'),
(N'om-KE', N'Oromo_Kenya_om-KE'),
(N'os', N'Ossetian_os'),
(N'os-GE', N'Ossetian_Cyrillic, Georgia_os-GE'),
(N'os-RU', N'Ossetian_Cyrillic, Russia_os-RU'),
(N'ps', N'Pashto_ps'),
(N'ps-AF', N'Pashto_Afghanistan_ps-AF'),
(N'fa', N'Persian_fa'),
(N'fa-AF', N'Persian_Afghanistan_fa-AF'),
(N'fa-IR', N'Persian_Iran_fa-IR'),
(N'pl', N'Polish_pl'),
(N'pl-PL', N'Polish_Poland_pl-PL'),
(N'pt', N'Portuguese_pt'),
(N'pt-AO', N'Portuguese_Angola_pt-AO'),
(N'pt-BR', N'Portuguese_Brazil_pt-BR'),
(N'pt-CV', N'Portuguese_Cabo Verde_pt-CV'),
(N'pt-GQ', N'Portuguese_Equatorial Guinea_pt-GQ'),
(N'pt-GW', N'Portuguese_Guinea-Bissau_pt-GW'),
(N'pt-LU', N'Portuguese_Luxembourg_pt-LU'),
(N'pt-MO', N'Portuguese_Macao SAR_pt-MO'),
(N'pt-MZ', N'Portuguese_Mozambique_pt-MZ'),
(N'pt-PT', N'Portuguese_Portugal_pt-PT'),
(N'pt-ST', N'Portuguese_São Tomé and Príncipe_pt-ST'),
(N'pt-CH', N'Portuguese_Switzerland_pt-CH'),
(N'pt-TL', N'Portuguese_Timor-Leste_pt-TL'),
(N'prg-001', N'Prussian_prg-001'),
(N'pa', N'Punjabi_pa'),
(N'pa-Arab', N'Punjabi_pa-Arab'),
(N'pa-IN', N'Punjabi_India_pa-IN'),
(N'pa-Arab-PK', N'Punjabi_Islamic Republic of Pakistan_pa-Arab-PK'),
(N'quz', N'Quechua_quz'),
(N'quz-BO', N'Quechua_Bolivia_quz-BO'),
(N'quz-EC', N'Quechua_Ecuador_quz-EC'),
(N'quz-PE', N'Quechua_Peru_quz-PE'),
(N'ksh', N'Ripuarian_ksh'),
(N'ksh-DE', N'Ripuarian_Germany_ksh-DE'),
(N'ro', N'Romanian_ro'),
(N'ro-MD', N'Romanian_Moldova_ro-MD'),
(N'ro-RO', N'Romanian_Romania_ro-RO'),
(N'rm', N'Romansh_rm'),
(N'rm-CH', N'Romansh_Switzerland_rm-CH'),
(N'rof', N'Rombo_rof'),
(N'rof-TZ', N'Rombo_Tanzania_rof-TZ'),
(N'rn', N'Rundi_rn'),
(N'rn-BI', N'Rundi_Burundi_rn-BI'),
(N'ru', N'Russian_ru'),
(N'ru-BY', N'Russian_Belarus_ru-BY'),
(N'ru-KZ', N'Russian_Kazakhstan_ru-KZ'),
(N'ru-KG', N'Russian_Kyrgyzstan_ru-KG'),
(N'ru-MD', N'Russian_Moldova_ru-MD'),
(N'ru-RU', N'Russian_Russia_ru-RU'),
(N'ru-UA', N'Russian_Ukraine_ru-UA'),
(N'rwk', N'Rwa_rwk'),
(N'rwk-TZ', N'Rwa_Tanzania_rwk-TZ'),
(N'ssy', N'Saho_ssy'),
(N'ssy-ER', N'Saho_Eritrea_ssy-ER'),
(N'sah', N'Sakha_sah'),
(N'sah-RU', N'Sakha_Russia_sah-RU'),
(N'saq', N'Samburu_saq'),
(N'saq-KE', N'Samburu_Kenya_saq-KE'),
(N'smn', N'Sami (Inari)_smn'),
(N'smn-FI', N'Sami (Inari)_Finland_smn-FI'),
(N'smj', N'Sami (Lule)_smj'),
(N'smj-NO', N'Sami (Lule)_Norway_smj-NO'),
(N'smj-SE', N'Sami (Lule)_Sweden_smj-SE'),
(N'se', N'Sami (Northern)_se'),
(N'se-FI', N'Sami (Northern)_Finland_se-FI'),
(N'se-NO', N'Sami (Northern)_Norway_se-NO'),
(N'se-SE', N'Sami (Northern)_Sweden_se-SE'),
(N'sms', N'Sami (Skolt)_sms'),
(N'sms-FI', N'Sami (Skolt)_Finland_sms-FI'),
(N'sma', N'Sami (Southern)_sma'),
(N'sma-NO', N'Sami (Southern)_Norway_sma-NO'),
(N'sma-SE', N'Sami (Southern)_Sweden_sma-SE'),
(N'sg', N'Sango_sg'),
(N'sg-CF', N'Sango_Central African Republic_sg-CF'),
(N'sbp', N'Sangu_sbp'),
(N'sbp-TZ', N'Sangu_Tanzania_sbp-TZ'),
(N'sa', N'Sanskrit_sa'),
(N'sa-IN', N'Sanskrit_India_sa-IN'),
(N'gd', N'Scottish Gaelic_gd'),
(N'gd-GB', N'Scottish Gaelic_United Kingdom_gd-GB'),
(N'seh', N'Sena_seh'),
(N'seh-MZ', N'Sena_Mozambique_seh-MZ'),
(N'sr-Cyrl', N'Serbian (Cyrillic)_sr-Cyrl'),
(N'sr-Cyrl-BA', N'Serbian (Cyrillic)_Bosnia and Herzegovina_sr-Cyrl-BA'),
(N'sr-Cyrl-ME', N'Serbian (Cyrillic)_Montenegro_sr-Cyrl-ME'),
(N'sr-Cyrl-RS', N'Serbian (Cyrillic)_Serbia_sr-Cyrl-RS'),
(N'sr-Cyrl-CS', N'Serbian (Cyrillic)_Serbia and Montenegro (Former)_sr-Cyrl-CS'),
(N'sr-Latn', N'Serbian (Latin)_sr-Latn'),
(N'sr', N'Serbian (Latin)_sr'),
(N'sr-Latn-BA', N'Serbian (Latin)_Bosnia and Herzegovina_sr-Latn-BA'),
(N'sr-Latn-ME', N'Serbian (Latin)_Montenegro_sr-Latn-ME'),
(N'sr-Latn-RS', N'Serbian (Latin)_Serbia_sr-Latn-RS'),
(N'sr-Latn-CS', N'Serbian (Latin)_Serbia and Montenegro (Former)_sr-Latn-CS'),
(N'nso', N'Sesotho sa Leboa_nso'),
(N'nso-ZA', N'Sesotho sa Leboa_South Africa_nso-ZA'),
(N'tn', N'Setswana_tn'),
(N'tn-BW', N'Setswana_Botswana_tn-BW'),
(N'tn-ZA', N'Setswana_South Africa_tn-ZA'),
(N'ksb', N'Shambala_ksb'),
(N'ksb-TZ', N'Shambala_Tanzania_ksb-TZ'),
(N'sn', N'Shona_sn'),
(N'sn-Latn', N'Shona_Latin_sn-Latn'),
(N'sn-Latn-ZW', N'Shona_Zimbabwe_sn-Latn-ZW'),
(N'sd', N'Sindhi_sd'),
(N'sd-Arab', N'Sindhi_sd-Arab'),
(N'sd-Arab-PK', N'Sindhi_Islamic Republic of Pakistan_sd-Arab-PK'),
(N'si', N'Sinhala_si'),
(N'si-LK', N'Sinhala_Sri Lanka_si-LK'),
(N'sk', N'Slovak_sk'),
(N'sk-SK', N'Slovak_Slovakia_sk-SK'),
(N'sl', N'Slovenian_sl'),
(N'sl-SI', N'Slovenian_Slovenia_sl-SI'),
(N'xog', N'Soga_xog'),
(N'xog-UG', N'Soga_Uganda_xog-UG'),
(N'so', N'Somali_so'),
(N'so-DJ', N'Somali_Djibouti_so-DJ'),
(N'so-ET', N'Somali_Ethiopia_so-ET'),
(N'so-KE', N'Somali_Kenya_so-KE'),
(N'so-SO', N'Somali_Somalia_so-SO'),
(N'st', N'Sotho_st'),
(N'st-ZA', N'Sotho_South Africa_st-ZA'),
(N'nr', N'South Ndebele_nr'),
(N'nr-ZA', N'South Ndebele_South Africa_nr-ZA'),
(N'st-LS', N'Southern Sotho_Lesotho_st-LS'),
(N'es', N'Spanish_es'),
(N'es-AR', N'Spanish_Argentina_es-AR'),
(N'es-BZ', N'Spanish_Belize_es-BZ'),
(N'es-VE', N'Spanish_Bolivarian Republic of Venezuela_es-VE'),
(N'es-BO', N'Spanish_Bolivia_es-BO'),
(N'es-BR', N'Spanish_Brazil_es-BR'),
(N'es-CL', N'Spanish_Chile_es-CL'),
(N'es-CO', N'Spanish_Colombia_es-CO'),
(N'es-CR', N'Spanish_Costa Rica_es-CR'),
(N'es-CU', N'Spanish_Cuba_es-CU'),
(N'es-DO', N'Spanish_Dominican Republic_es-DO'),
(N'es-EC', N'Spanish_Ecuador_es-EC'),
(N'es-SV', N'Spanish_El Salvador_es-SV'),
(N'es-GQ', N'Spanish_Equatorial Guinea_es-GQ'),
(N'es-GT', N'Spanish_Guatemala_es-GT'),
(N'es-HN', N'Spanish_Honduras_es-HN'),
(N'es-419', N'Spanish_Latin America_es-419'),
(N'es-MX', N'Spanish_Mexico_es-MX'),
(N'es-NI', N'Spanish_Nicaragua_es-NI'),
(N'es-PA', N'Spanish_Panama_es-PA'),
(N'es-PY', N'Spanish_Paraguay_es-PY'),
(N'es-PE', N'Spanish_Peru_es-PE'),
(N'es-PH', N'Spanish_Philippines_es-PH'),
(N'es-PR', N'Spanish_Puerto Rico_es-PR'),
(N'es-ES_tradnl', N'Spanish_Spain_es-ES_tradnl'),
(N'es-ES', N'Spanish_Spain_es-ES'),
(N'es-US', N'Spanish_United States_es-US'),
(N'es-UY', N'Spanish_Uruguay_es-UY'),
(N'zgh', N'Standard Moroccan Tamazight_zgh'),
(N'zgh-Tfng-MA', N'Standard Moroccan Tamazight_Morocco_zgh-Tfng-MA'),
(N'zgh-Tfng', N'Standard Moroccan Tamazight_Tifinagh_zgh-Tfng'),
(N'ss', N'Swati_ss'),
(N'ss-ZA', N'Swati_South Africa_ss-ZA'),
(N'ss-SZ', N'Swati_Swaziland_ss-SZ'),
(N'sv', N'Swedish_sv'),
(N'sv-AX', N'Swedish_Åland Islands_sv-AX'),
(N'sv-FI', N'Swedish_Finland_sv-FI'),
(N'sv-SE', N'Swedish_Sweden_sv-SE'),
(N'syr', N'Syriac_syr'),
(N'syr-SY', N'Syriac_Syria_syr-SY'),
(N'shi', N'Tachelhit_shi'),
(N'shi-Tfng', N'Tachelhit_Tifinagh_shi-Tfng'),
(N'shi-Tfng-MA', N'Tachelhit_Tifinagh, Morocco_shi-Tfng-MA'),
(N'shi-Latn', N'Tachelhit (Latin)_shi-Latn'),
(N'shi-Latn-MA', N'Tachelhit (Latin)_Morocco_shi-Latn-MA'),
(N'dav', N'Taita_dav'),
(N'dav-KE', N'Taita_Kenya_dav-KE'),
(N'tg', N'Tajik (Cyrillic)_tg'),
(N'tg-Cyrl', N'Tajik (Cyrillic)_tg-Cyrl'),
(N'tg-Cyrl-TJ', N'Tajik (Cyrillic)_Tajikistan_tg-Cyrl-TJ'),
(N'tzm', N'Tamazight (Latin)_tzm'),
(N'tzm-Latn', N'Tamazight (Latin)_tzm-Latn'),
(N'tzm-Latn-DZ', N'Tamazight (Latin)_Algeria_tzm-Latn-DZ'),
(N'ta', N'Tamil_ta'),
(N'ta-IN', N'Tamil_India_ta-IN'),
(N'ta-MY', N'Tamil_Malaysia_ta-MY'),
(N'ta-SG', N'Tamil_Singapore_ta-SG'),
(N'ta-LK', N'Tamil_Sri Lanka_ta-LK'),
(N'twq', N'Tasawaq_twq'),
(N'twq-NE', N'Tasawaq_Niger_twq-NE'),
(N'tt', N'Tatar_tt'),
(N'tt-RU', N'Tatar_Russia_tt-RU'),
(N'te', N'Telugu_te'),
(N'te-IN', N'Telugu_India_te-IN'),
(N'teo', N'Teso_teo'),
(N'teo-KE', N'Teso_Kenya_teo-KE'),
(N'teo-UG', N'Teso_Uganda_teo-UG'),
(N'th', N'Thai_th'),
(N'th-TH', N'Thai_Thailand_th-TH'),
(N'bo', N'Tibetan_bo'),
(N'bo-IN', N'Tibetan_India_bo-IN'),
(N'bo-CN', N'Tibetan_People''s Republic of China_bo-CN'),
(N'tig', N'Tigre_tig'),
(N'tig-ER', N'Tigre_Eritrea_tig-ER'),
(N'ti', N'Tigrinya_ti'),
(N'ti-ER', N'Tigrinya_Eritrea_ti-ER'),
(N'ti-ET', N'Tigrinya_Ethiopia_ti-ET'),
(N'to', N'Tongan_to'),
(N'to-TO', N'Tongan_Tonga_to-TO'),
(N'ts', N'Tsonga_ts'),
(N'ts-ZA', N'Tsonga_South Africa_ts-ZA'),
(N'tr', N'Turkish_tr'),
(N'tr-CY', N'Turkish_Cyprus_tr-CY'),
(N'tr-TR', N'Turkish_Turkey_tr-TR'),
(N'tk', N'Turkmen_tk'),
(N'tk-TM', N'Turkmen_Turkmenistan_tk-TM'),
(N'uk', N'Ukrainian_uk'),
(N'uk-UA', N'Ukrainian_Ukraine_uk-UA'),
(N'dsb or hsb', N'Upper Sorbian_dsb or hsb'),
(N'hsb-DE', N'Upper Sorbian_Germany_hsb-DE'),
(N'ur', N'Urdu_ur'),
(N'ur-IN', N'Urdu_India_ur-IN'),
(N'ur-PK', N'Urdu_Islamic Republic of Pakistan_ur-PK'),
(N'ug', N'Uyghur_ug'),
(N'ug-CN', N'Uyghur_People''s Republic of China_ug-CN'),
(N'uz-Arab', N'Uzbek_Perso-Arabic_uz-Arab'),
(N'uz-Arab-AF', N'Uzbek_Perso-Arabic, Afghanistan_uz-Arab-AF'),
(N'uz-Cyrl', N'Uzbek (Cyrillic)_uz-Cyrl'),
(N'uz-Cyrl-UZ', N'Uzbek (Cyrillic)_Uzbekistan_uz-Cyrl-UZ'),
(N'uz', N'Uzbek (Latin)_uz'),
(N'uz-Latn', N'Uzbek (Latin)_uz-Latn'),
(N'uz-Latn-UZ', N'Uzbek (Latin)_Uzbekistan_uz-Latn-UZ'),
(N'vai', N'Vai_vai'),
(N'vai-Vaii', N'Vai_vai-Vaii'),
(N'vai-Vaii-LR', N'Vai_Liberia_vai-Vaii-LR'),
(N'vai-Latn-LR', N'Vai (Latin)_ Liberia_vai-Latn-LR'),
(N'vai-Latn', N'Vai (Latin)_vai-Latn'),
(N'ca-ES-valencia', N'Valencian_Spain_ca-ES-valencia'),
(N've', N'Venda_ve'),
(N've-ZA', N'Venda_South Africa_ve-ZA'),
(N'vi', N'Vietnamese_vi'),
(N'vi-VN', N'Vietnamese_Vietnam_vi-VN'),
(N'vo', N'Volapük_vo'),
(N'vo-001', N'Volapük_World_vo-001'),
(N'vun', N'Vunjo_vun'),
(N'vun-TZ', N'Vunjo_Tanzania_vun-TZ'),
(N'wae', N'Walser_wae'),
(N'wae-CH', N'Walser_Switzerland_wae-CH'),
(N'cy', N'Welsh_cy'),
(N'cy-GB', N'Welsh_United Kingdom_cy-GB'),
(N'wal', N'Wolaytta_wal'),
(N'wal-ET', N'Wolaytta_Ethiopia_wal-ET'),
(N'wo', N'Wolof_wo'),
(N'wo-SN', N'Wolof_Senegal_wo-SN'),
(N'xh', N'Xhosa_xh'),
(N'xh-ZA', N'Xhosa_South Africa_xh-ZA'),
(N'yav', N'Yangben_yav'),
(N'yav-CM', N'Yangben_Cameroon_yav-CM'),
(N'ii', N'Yi_ii'),
(N'ii-CN', N'Yi_People''s Republic of China_ii-CN'),
(N'yo', N'Yoruba_yo'),
(N'yo-BJ', N'Yoruba_Benin_yo-BJ'),
(N'yo-NG', N'Yoruba_Nigeria_yo-NG'),
(N'dje', N'Zarma_dje'),
(N'dje-NE', N'Zarma_Niger_dje-NE'),
(N'zu', N'Zulu_zu'),
(N'zu-ZA', N'Zulu_South Africa_zu-ZA')
